-- Fiche La soustraction (CE2) - notion 'soustraction'. Relancer ce script remplace le contenu de la fiche.
insert into contenu_cours (classe, matiere, titre, contenu, statut, notion_id)
select 'ce2', 'math', 'La soustraction', $fiche$
[titre]Soustraire, rappel[/titre]
Soustraire, c'est [b]enlever[/b] ou chercher [b]l'écart[/b]. Le résultat s'appelle [b]la différence[/b].
Enlever des centaines ou des milliers se fait de tête :
[table=2][cell bg=#centaines_clair border=#centaines padding=14,6,14,6][b]5676 - 300 = 5376[/b][/cell][cell border=#centaines padding=14,6,14,6]le chiffre des [b]centaines[/b] passe de 6 à 3[/cell][cell bg=#milliers_clair border=#milliers padding=14,6,14,6][b]5676 - 2000 = 3676[/b][/cell][cell border=#milliers padding=14,6,14,6]le chiffre des [b]milliers[/b] passe de 5 à 3[/cell][/table]
[page]
[titre]Poser une soustraction[/titre]
J'aligne les nombres [b]à droite[/b] et je commence par [b]les unités[/b].
[table=5][cell padding=10,4,10,4][/cell][cell bg=#milliers border=#milliers padding=18,4,18,4][center][color=white][b]M[/b][/color][/center][/cell][cell bg=#centaines border=#centaines padding=18,4,18,4][center][color=white][b]C[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=18,4,18,4][center][color=white][b]D[/b][/color][/center][/cell][cell bg=#unites border=#unites padding=18,4,18,4][center][color=white][b]U[/b][/color][/center][/cell][cell padding=10,4,10,4][b][/b][/cell][cell border=#milliers padding=18,4,18,4][center][b]5[/b][/center][/cell][cell border=#centaines padding=18,4,18,4][center][b]6[/b][/center][/cell][cell border=#classe padding=18,4,18,4][center][b]7[/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b]6[/b][/center][/cell][cell padding=10,4,10,4][b]-[/b][/cell][cell border=#milliers padding=18,4,18,4][/cell][cell border=#centaines padding=18,4,18,4][center][b]1[/b][/center][/cell][cell border=#classe padding=18,4,18,4][center][b]4[/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b]3[/b][/center][/cell][cell padding=10,4,10,4][b]=[/b][/cell][cell bg=#milliers_clair border=#milliers padding=18,4,18,4][center][b]5[/b][/center][/cell][cell bg=#centaines_clair border=#centaines padding=18,4,18,4][center][b]5[/b][/center][/cell][cell bg=#classe_clair border=#classe padding=18,4,18,4][center][b]3[/b][/center][/cell][cell bg=#unites_clair border=#unites padding=18,4,18,4][center][b]3[/b][/center][/cell][/table]
[cadre]Unités : 6 - 3 = 3. Dizaines : 7 - 4 = 3. Centaines : 6 - 1 = 5. Milliers : 5.
[b]5676 - 143 = 5533[/b][/cadre]
[page]
[titre]Pas assez dans une colonne ?[/titre]
Pour [b]4352 - 1236[/b] : dans les unités, 2 - 6, c'est impossible.
Comme au CE1, il existe [b]deux méthodes[/b] :
[table=2][cell bg=#classe_clair border=#classe padding=14,6,14,6][center][b]Méthode 1 : le cassage[/b][/center][/cell][cell bg=#unites_clair border=#unites padding=14,6,14,6][center][b]Méthode 2 : la compensation[/b][/center][/cell][cell border=#classe padding=14,6,14,6]je casse une dizaine du nombre du haut[/cell][cell border=#unites padding=14,6,14,6]j'ajoute 10 en haut et 1 dizaine en bas[/cell][/table]
[cadre]Les deux méthodes donnent [b]le même résultat[/b].
C'est [b]ton école[/b] qui choisit : utilise toujours [b]la méthode de ta classe[/b].[/cadre]
[page]
[titre]Méthode 1 : le cassage[/titre]
Je casse une dizaine de 4352 : le 5 des dizaines devient 4, et le 2 des unités devient 12.
[table=5][cell padding=10,4,10,4][/cell][cell bg=#milliers border=#milliers padding=18,4,18,4][center][color=white][b]M[/b][/color][/center][/cell][cell bg=#centaines border=#centaines padding=18,4,18,4][center][color=white][b]C[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=18,4,18,4][center][color=white][b]D[/b][/color][/center][/cell][cell bg=#unites border=#unites padding=18,4,18,4][center][color=white][b]U[/b][/color][/center][/cell][cell padding=10,0,10,0][/cell][cell padding=18,0,18,0][/cell][cell padding=18,0,18,0][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]4[/b][/color][/font_size][/center][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]12[/b][/color][/font_size][/center][/cell][cell padding=10,4,10,4][b][/b][/cell][cell border=#milliers padding=18,4,18,4][center][b]4[/b][/center][/cell][cell border=#centaines padding=18,4,18,4][center][b]3[/b][/center][/cell][cell border=#classe padding=18,4,18,4][center][b][color=#C62828][s]5[/s][/color][/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b][color=#C62828][s]2[/s][/color][/b][/center][/cell][cell padding=10,4,10,4][b]-[/b][/cell][cell border=#milliers padding=18,4,18,4][center][b]1[/b][/center][/cell][cell border=#centaines padding=18,4,18,4][center][b]2[/b][/center][/cell][cell border=#classe padding=18,4,18,4][center][b]3[/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b]6[/b][/center][/cell][cell padding=10,4,10,4][b]=[/b][/cell][cell bg=#milliers_clair border=#milliers padding=18,4,18,4][center][b]3[/b][/center][/cell][cell bg=#centaines_clair border=#centaines padding=18,4,18,4][center][b]1[/b][/center][/cell][cell bg=#classe_clair border=#classe padding=18,4,18,4][center][b]1[/b][/center][/cell][cell bg=#unites_clair border=#unites padding=18,4,18,4][center][b]6[/b][/center][/cell][/table]
Unités : 12 - 6 = 6. Dizaines : 4 - 3 = 1. Centaines : 3 - 2 = 1. Milliers : 4 - 1 = 3.
[cadre][b]4352 - 1236 = 3116[/b][/cadre]
[page]
[titre]Méthode 2 : la compensation[/titre]
J'ajoute 10 unités en haut (2 devient 12) et 1 dizaine en bas (3 devient 4) : l'écart ne change pas.
[table=5][cell padding=10,4,10,4][/cell][cell bg=#milliers border=#milliers padding=18,4,18,4][center][color=white][b]M[/b][/color][/center][/cell][cell bg=#centaines border=#centaines padding=18,4,18,4][center][color=white][b]C[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=18,4,18,4][center][color=white][b]D[/b][/color][/center][/cell][cell bg=#unites border=#unites padding=18,4,18,4][center][color=white][b]U[/b][/color][/center][/cell][cell padding=10,4,10,4][b][/b][/cell][cell border=#milliers padding=18,4,18,4][center][b]4[/b][/center][/cell][cell border=#centaines padding=18,4,18,4][center][b]3[/b][/center][/cell][cell border=#classe padding=18,4,18,4][center][b]5[/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b][color=#C62828][font_size=18]1[/font_size][/color]2[/b][/center][/cell][cell padding=10,4,10,4][b]-[/b][/cell][cell border=#milliers padding=18,4,18,4][center][b]1[/b][/center][/cell][cell border=#centaines padding=18,4,18,4][center][b]2[/b][/center][/cell][cell border=#classe padding=18,4,18,4][center][b]3[color=#C62828][font_size=18]+1[/font_size][/color][/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b]6[/b][/center][/cell][cell padding=10,4,10,4][b]=[/b][/cell][cell bg=#milliers_clair border=#milliers padding=18,4,18,4][center][b]3[/b][/center][/cell][cell bg=#centaines_clair border=#centaines padding=18,4,18,4][center][b]1[/b][/center][/cell][cell bg=#classe_clair border=#classe padding=18,4,18,4][center][b]1[/b][/center][/cell][cell bg=#unites_clair border=#unites padding=18,4,18,4][center][b]6[/b][/center][/cell][/table]
Unités : 12 - 6 = 6. Dizaines : 5 - (3 + 1) = 5 - 4 = 1. Centaines : 3 - 2 = 1. Milliers : 4 - 1 = 3.
[cadre][b]4352 - 1236 = 3116[/b] : le même résultat qu'avec le cassage ![/cadre]
[page]
[titre]Avec un zéro[/titre]
Pour [b]7088 - 1868[/b] : centaines, 0 - 8, impossible ! Je travaille avec [b]les milliers[/b].
[table=5][cell padding=10,4,10,4][/cell][cell bg=#milliers border=#milliers padding=18,4,18,4][center][color=white][b]M[/b][/color][/center][/cell][cell bg=#centaines border=#centaines padding=18,4,18,4][center][color=white][b]C[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=18,4,18,4][center][color=white][b]D[/b][/color][/center][/cell][cell bg=#unites border=#unites padding=18,4,18,4][center][color=white][b]U[/b][/color][/center][/cell][cell padding=10,0,10,0][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]6[/b][/color][/font_size][/center][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]10[/b][/color][/font_size][/center][/cell][cell padding=18,0,18,0][/cell][cell padding=18,0,18,0][/cell][cell padding=10,4,10,4][b][/b][/cell][cell border=#milliers padding=18,4,18,4][center][b][color=#C62828][s]7[/s][/color][/b][/center][/cell][cell border=#centaines padding=18,4,18,4][center][b][color=#C62828][s]0[/s][/color][/b][/center][/cell][cell border=#classe padding=18,4,18,4][center][b]8[/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b]8[/b][/center][/cell][cell padding=10,4,10,4][b]-[/b][/cell][cell border=#milliers padding=18,4,18,4][center][b]1[/b][/center][/cell][cell border=#centaines padding=18,4,18,4][center][b]8[/b][/center][/cell][cell border=#classe padding=18,4,18,4][center][b]6[/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b]8[/b][/center][/cell][cell padding=10,4,10,4][b]=[/b][/cell][cell bg=#milliers_clair border=#milliers padding=18,4,18,4][center][b]5[/b][/center][/cell][cell bg=#centaines_clair border=#centaines padding=18,4,18,4][center][b]2[/b][/center][/cell][cell bg=#classe_clair border=#classe padding=18,4,18,4][center][b]2[/b][/center][/cell][cell bg=#unites_clair border=#unites padding=18,4,18,4][center][b]0[/b][/center][/cell][/table]
Cassage : je casse un millier. 7 milliers 0 centaine → 6 milliers 10 centaines. 10 - 8 = 2, puis 6 - 1 = 5.
[cadre=astuce]Compensation : j'ajoute 10 centaines en haut (0 → 10) et 1 millier en bas (1 → 2).
10 - 8 = 2, puis 7 - 2 = 5. Même résultat : [b]5220[/b].[/cadre]
[page]
[titre]Plusieurs fois dans la même opération[/titre]
Pour [b]6733 - 3957[/b], il manque dans [b]chaque colonne[/b] : je recommence à chaque fois.
[table=5][cell padding=10,4,10,4][/cell][cell bg=#milliers border=#milliers padding=18,4,18,4][center][color=white][b]M[/b][/color][/center][/cell][cell bg=#centaines border=#centaines padding=18,4,18,4][center][color=white][b]C[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=18,4,18,4][center][color=white][b]D[/b][/color][/center][/cell][cell bg=#unites border=#unites padding=18,4,18,4][center][color=white][b]U[/b][/color][/center][/cell][cell padding=10,0,10,0][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]5[/b][/color][/font_size][/center][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]16[/b][/color][/font_size][/center][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]12[/b][/color][/font_size][/center][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]13[/b][/color][/font_size][/center][/cell][cell padding=10,4,10,4][b][/b][/cell][cell border=#milliers padding=18,4,18,4][center][b][color=#C62828][s]6[/s][/color][/b][/center][/cell][cell border=#centaines padding=18,4,18,4][center][b][color=#C62828][s]7[/s][/color][/b][/center][/cell][cell border=#classe padding=18,4,18,4][center][b][color=#C62828][s]3[/s][/color][/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b][color=#C62828][s]3[/s][/color][/b][/center][/cell][cell padding=10,4,10,4][b]-[/b][/cell][cell border=#milliers padding=18,4,18,4][center][b]3[/b][/center][/cell][cell border=#centaines padding=18,4,18,4][center][b]9[/b][/center][/cell][cell border=#classe padding=18,4,18,4][center][b]5[/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b]7[/b][/center][/cell][cell padding=10,4,10,4][b]=[/b][/cell][cell bg=#milliers_clair border=#milliers padding=18,4,18,4][center][b]2[/b][/center][/cell][cell bg=#centaines_clair border=#centaines padding=18,4,18,4][center][b]7[/b][/center][/cell][cell bg=#classe_clair border=#classe padding=18,4,18,4][center][b]7[/b][/center][/cell][cell bg=#unites_clair border=#unites padding=18,4,18,4][center][b]6[/b][/center][/cell][/table]
Unités : 13 - 7 = 6. Dizaines : 12 - 5 = 7. Centaines : 16 - 9 = 7. Milliers : 5 - 3 = 2.
[cadre=astuce]Avec la compensation, c'est pareil : colonne après colonne, 10 en haut et 1 de plus en bas.[/cadre]
[page]
[titre]Vérifier avec une addition[/titre]
J'ajoute ce que j'ai enlevé : je dois retrouver le nombre du départ.
[table=5][cell padding=10,4,10,4][/cell][cell bg=#milliers border=#milliers padding=18,4,18,4][center][color=white][b]M[/b][/color][/center][/cell][cell bg=#centaines border=#centaines padding=18,4,18,4][center][color=white][b]C[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=18,4,18,4][center][color=white][b]D[/b][/color][/center][/cell][cell bg=#unites border=#unites padding=18,4,18,4][center][color=white][b]U[/b][/color][/center][/cell][cell padding=10,0,10,0][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]1[/b][/color][/font_size][/center][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]1[/b][/color][/font_size][/center][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]1[/b][/color][/font_size][/center][/cell][cell padding=18,0,18,0][/cell][cell padding=10,4,10,4][b][/b][/cell][cell border=#milliers padding=18,4,18,4][center][b]2[/b][/center][/cell][cell border=#centaines padding=18,4,18,4][center][b]7[/b][/center][/cell][cell border=#classe padding=18,4,18,4][center][b]7[/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b]6[/b][/center][/cell][cell padding=10,4,10,4][b]+[/b][/cell][cell border=#milliers padding=18,4,18,4][center][b]3[/b][/center][/cell][cell border=#centaines padding=18,4,18,4][center][b]9[/b][/center][/cell][cell border=#classe padding=18,4,18,4][center][b]5[/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b]7[/b][/center][/cell][cell padding=10,4,10,4][b]=[/b][/cell][cell bg=#milliers_clair border=#milliers padding=18,4,18,4][center][b]6[/b][/center][/cell][cell bg=#centaines_clair border=#centaines padding=18,4,18,4][center][b]7[/b][/center][/cell][cell bg=#classe_clair border=#classe padding=18,4,18,4][center][b]3[/b][/center][/cell][cell bg=#unites_clair border=#unites padding=18,4,18,4][center][b]3[/b][/center][/cell][/table]
[cadre]2776 + 3957 = 6733 : c'est bien le nombre du départ, ma soustraction est juste.[/cadre]
[page]
[titre]Je retiens[/titre]
[cadre]• Soustraire, c'est enlever ou chercher l'écart. Le résultat est [b]la différence[/b].
• Pour poser : j'aligne à droite et je commence par les [b]unités[/b].
• Pas assez dans une colonne ? Le [b]cassage[/b] ou la [b]compensation[/b] : j'utilise [b]la méthode de ma classe[/b].
• Avec un 0 en haut, je passe par la colonne d'à côté : 1 millier = 10 centaines.
• Il peut manquer dans plusieurs colonnes : je recommence à chaque fois.
• Je vérifie avec une addition.[/cadre]
$fiche$, 'publie', n.id from contenu_notions n where n.code = 'soustraction'
on conflict (notion_id, classe) where statut <> 'archive'
do update set titre = excluded.titre, contenu = excluded.contenu, statut = 'publie', modifie_le = now()
returning id, titre, statut;
select fn_publier();
