-- Fiche La soustraction (CM1) - notion 'soustraction'. Relancer ce script remplace le contenu de la fiche.
insert into contenu_cours (classe, matiere, titre, contenu, statut, notion_id)
select 'cm1', 'math', 'La soustraction', $fiche$
[titre]Soustraire des décimaux[/titre]
Comme pour l'addition : [b]virgule sous virgule[/b], et je commence par la droite.
[table=6][cell padding=10,4,10,4][/cell][cell bg=#classe border=#classe padding=18,4,18,4][center][color=white][b]D[/b][/color][/center][/cell][cell bg=#unites border=#unites padding=18,4,18,4][center][color=white][b]U[/b][/color][/center][/cell][cell padding=6,4,6,4][/cell][cell bg=#dixiemes border=#dixiemes padding=18,4,18,4][center][color=white][b]1/10[/b][/color][/center][/cell][cell bg=#centiemes border=#centiemes padding=18,4,18,4][center][color=white][b]1/100[/b][/color][/center][/cell][cell padding=10,4,10,4][b][/b][/cell][cell border=#classe padding=18,4,18,4][center][b]1[/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b]7[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b]8[/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b]7[/b][/center][/cell][cell padding=10,4,10,4][b]-[/b][/cell][cell border=#classe padding=18,4,18,4][center][b]1[/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b]4[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b]7[/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b]7[/b][/center][/cell][cell padding=10,4,10,4][b]=[/b][/cell][cell bg=#classe_clair border=#classe padding=18,4,18,4][/cell][cell bg=#unites_clair border=#unites padding=18,4,18,4][center][b]3[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell bg=#dixiemes_clair border=#dixiemes padding=18,4,18,4][center][b]1[/b][/center][/cell][cell bg=#centiemes_clair border=#centiemes padding=18,4,18,4][center][b]0[/b][/center][/cell][/table]
[cadre]17,87 - 14,77 = [b]3,10[/b]. Le 0 à la fin ne sert à rien : 3,10 = [b]3,1[/b].[/cadre]
[page]
[titre]Pas assez dans une colonne ?[/titre]
Pour [b]15,28 - 8,94[/b] : dixièmes, 2 - 9, impossible ! Puis unités, 5 - 8, impossible aussi.
Tu connais [b]deux méthodes[/b], elles marchent aussi avec la virgule :
[table=2][cell bg=#classe_clair border=#classe padding=14,6,14,6][center][b]Le cassage[/b][/center][/cell][cell bg=#unites_clair border=#unites padding=14,6,14,6][center][b]La compensation[/b][/center][/cell][cell border=#classe padding=14,6,14,6]je casse 1 unité en 10 dixièmes[/cell][cell border=#unites padding=14,6,14,6]10 dixièmes en haut, 1 unité en bas[/cell][/table]
[cadre]Garde [b]la méthode de ta classe[/b] : les deux donnent le même résultat.[/cadre]
[page]
[titre]Méthode 1 : le cassage[/titre]
[table=6][cell padding=10,4,10,4][/cell][cell bg=#classe border=#classe padding=18,4,18,4][center][color=white][b]D[/b][/color][/center][/cell][cell bg=#unites border=#unites padding=18,4,18,4][center][color=white][b]U[/b][/color][/center][/cell][cell padding=6,4,6,4][/cell][cell bg=#dixiemes border=#dixiemes padding=18,4,18,4][center][color=white][b]1/10[/b][/color][/center][/cell][cell bg=#centiemes border=#centiemes padding=18,4,18,4][center][color=white][b]1/100[/b][/color][/center][/cell][cell padding=10,0,10,0][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]0[/b][/color][/font_size][/center][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]14[/b][/color][/font_size][/center][/cell][cell padding=6,0,6,0][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]12[/b][/color][/font_size][/center][/cell][cell padding=6,0,6,0][/cell][cell padding=10,4,10,4][b][/b][/cell][cell border=#classe padding=18,4,18,4][center][b][color=#C62828][s]1[/s][/color][/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b][color=#C62828][s]5[/s][/color][/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b][color=#C62828][s]2[/s][/color][/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b]8[/b][/center][/cell][cell padding=10,4,10,4][b]-[/b][/cell][cell border=#classe padding=18,4,18,4][/cell][cell border=#unites padding=18,4,18,4][center][b]8[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b]9[/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b]4[/b][/center][/cell][cell padding=10,4,10,4][b]=[/b][/cell][cell bg=#classe_clair border=#classe padding=18,4,18,4][/cell][cell bg=#unites_clair border=#unites padding=18,4,18,4][center][b]6[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell bg=#dixiemes_clair border=#dixiemes padding=18,4,18,4][center][b]3[/b][/center][/cell][cell bg=#centiemes_clair border=#centiemes padding=18,4,18,4][center][b]4[/b][/center][/cell][/table]
Centièmes : 8 - 4 = 4. Dixièmes : je casse 1 unité, 2 devient [b]12[/b] : 12 - 9 = 3.
Unités : il reste 4, je casse 1 dizaine, 4 devient [b]14[/b] : 14 - 8 = 6. Dizaines : 0.
[cadre][b]15,28 - 8,94 = 6,34[/b][/cadre]
[page]
[titre]Méthode 2 : la compensation[/titre]
[table=6][cell padding=10,4,10,4][/cell][cell bg=#classe border=#classe padding=18,4,18,4][center][color=white][b]D[/b][/color][/center][/cell][cell bg=#unites border=#unites padding=18,4,18,4][center][color=white][b]U[/b][/color][/center][/cell][cell padding=6,4,6,4][/cell][cell bg=#dixiemes border=#dixiemes padding=18,4,18,4][center][color=white][b]1/10[/b][/color][/center][/cell][cell bg=#centiemes border=#centiemes padding=18,4,18,4][center][color=white][b]1/100[/b][/color][/center][/cell][cell padding=10,4,10,4][b][/b][/cell][cell border=#classe padding=18,4,18,4][center][b]1[/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b][color=#C62828][font_size=18]1[/font_size][/color]5[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b][color=#C62828][font_size=18]1[/font_size][/color]2[/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b]8[/b][/center][/cell][cell padding=10,4,10,4][b]-[/b][/cell][cell border=#classe padding=18,4,18,4][center][b][color=#C62828][font_size=18]+1[/font_size][/color][/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b]8[color=#C62828][font_size=18]+1[/font_size][/color][/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b]9[/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b]4[/b][/center][/cell][cell padding=10,4,10,4][b]=[/b][/cell][cell bg=#classe_clair border=#classe padding=18,4,18,4][/cell][cell bg=#unites_clair border=#unites padding=18,4,18,4][center][b]6[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell bg=#dixiemes_clair border=#dixiemes padding=18,4,18,4][center][b]3[/b][/center][/cell][cell bg=#centiemes_clair border=#centiemes padding=18,4,18,4][center][b]4[/b][/center][/cell][/table]
Centièmes : 8 - 4 = 4. Dixièmes : 10 dixièmes en haut (12) et 1 unité en bas (8 + 1 = 9) : 12 - 9 = 3.
Unités : 10 unités en haut (15) et 1 dizaine en bas : 15 - 9 = 6. Dizaines : 1 - 1 = 0.
[cadre]Même résultat : [b]6,34[/b].[/cadre]
[page]
[titre]Soustraire d'un nombre rond[/titre]
Pour [b]10 - 3,46[/b], je peux poser 10,00 - 3,46. Ou j'avance [b]par bonds[/b] de 3,46 jusqu'à 10 :
[table=3][cell bg=#classe_clair border=#classe padding=14,6,14,6][center]3,46 → 4[/center][/cell][cell bg=#unites_clair border=#unites padding=14,6,14,6][center]4 → 10[/center][/cell][cell bg=#centaines_clair border=#centaines padding=14,6,14,6][center][b]En tout[/b][/center][/cell][cell border=#classe padding=14,6,14,6][center][b]+ 0,54[/b][/center][/cell][cell border=#unites padding=14,6,14,6][center][b]+ 6[/b][/center][/cell][cell border=#centaines padding=14,6,14,6][center][b]6 + 0,54 = 6,54[/b][/center][/cell][/table]
[cadre][b]10 - 3,46 = 6,54[/b]. Pour aller à 4, il manque 54 centièmes : 46 + 54 = 100.[/cadre]
[page]
[titre]Vérifier avec une addition[/titre]
J'ajoute ce que j'ai enlevé : je dois retrouver le nombre du départ.
[table=6][cell padding=10,4,10,4][/cell][cell bg=#classe border=#classe padding=18,4,18,4][center][color=white][b]D[/b][/color][/center][/cell][cell bg=#unites border=#unites padding=18,4,18,4][center][color=white][b]U[/b][/color][/center][/cell][cell padding=6,4,6,4][/cell][cell bg=#dixiemes border=#dixiemes padding=18,4,18,4][center][color=white][b]1/10[/b][/color][/center][/cell][cell bg=#centiemes border=#centiemes padding=18,4,18,4][center][color=white][b]1/100[/b][/color][/center][/cell][cell padding=10,0,10,0][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]1[/b][/color][/font_size][/center][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]1[/b][/color][/font_size][/center][/cell][cell padding=6,0,6,0][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]1[/b][/color][/font_size][/center][/cell][cell padding=6,0,6,0][/cell][cell padding=10,4,10,4][b][/b][/cell][cell border=#classe padding=18,4,18,4][/cell][cell border=#unites padding=18,4,18,4][center][b]6[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b]5[/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b]4[/b][/center][/cell][cell padding=10,4,10,4][b]+[/b][/cell][cell border=#classe padding=18,4,18,4][/cell][cell border=#unites padding=18,4,18,4][center][b]3[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b]4[/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b]6[/b][/center][/cell][cell padding=10,4,10,4][b]=[/b][/cell][cell bg=#classe_clair border=#classe padding=18,4,18,4][center][b]1[/b][/center][/cell][cell bg=#unites_clair border=#unites padding=18,4,18,4][center][b]0[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell bg=#dixiemes_clair border=#dixiemes padding=18,4,18,4][center][b]0[/b][/center][/cell][cell bg=#centiemes_clair border=#centiemes padding=18,4,18,4][center][b]0[/b][/center][/cell][/table]
[cadre]6,54 + 3,46 = 10 : ma soustraction est juste.[/cadre]
[page]
[titre]Je retiens[/titre]
[cadre]• [b]Virgule sous virgule[/b], et je complète avec des 0 : 10 = 10,00.
• Je commence par la droite. Pas assez ? Cassage ou compensation : [b]la méthode de ma classe[/b].
• 3,10 = 3,1 : un 0 tout à la fin de la partie décimale ne change rien.
• Pour un nombre rond, j'avance par bonds : 3,46 → 4 → 10.
• Je vérifie avec une addition.[/cadre]
$fiche$, 'publie', n.id from contenu_notions n where n.code = 'soustraction'
on conflict (notion_id, classe) where statut <> 'archive'
do update set titre = excluded.titre, contenu = excluded.contenu, statut = 'publie', modifie_le = now()
returning id, titre, statut;
select fn_publier();
