-- Fiche La soustraction (CM2) - notion 'soustraction'. Relancer ce script remplace le contenu de la fiche.
insert into contenu_cours (classe, matiere, titre, contenu, statut, notion_id)
select 'cm2', 'math', 'La soustraction', $fiche$
[titre]Le cassage, avec la virgule[/titre]
Pour [b]11,32 - 5,53[/b], il manque dans [b]chaque colonne[/b] : je casse à chaque fois.
[table=6][cell padding=10,4,10,4][/cell][cell bg=#classe border=#classe padding=18,4,18,4][center][color=white][b]D[/b][/color][/center][/cell][cell bg=#unites border=#unites padding=18,4,18,4][center][color=white][b]U[/b][/color][/center][/cell][cell padding=6,4,6,4][/cell][cell bg=#dixiemes border=#dixiemes padding=18,4,18,4][center][color=white][b]1/10[/b][/color][/center][/cell][cell bg=#centiemes border=#centiemes padding=18,4,18,4][center][color=white][b]1/100[/b][/color][/center][/cell][cell padding=10,0,10,0][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]0[/b][/color][/font_size][/center][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]10[/b][/color][/font_size][/center][/cell][cell padding=6,0,6,0][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]12[/b][/color][/font_size][/center][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]12[/b][/color][/font_size][/center][/cell][cell padding=10,4,10,4][b][/b][/cell][cell border=#classe padding=18,4,18,4][center][b][color=#C62828][s]1[/s][/color][/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b][color=#C62828][s]1[/s][/color][/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b][color=#C62828][s]3[/s][/color][/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b][color=#C62828][s]2[/s][/color][/b][/center][/cell][cell padding=10,4,10,4][b]-[/b][/cell][cell border=#classe padding=18,4,18,4][/cell][cell border=#unites padding=18,4,18,4][center][b]5[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b]5[/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b]3[/b][/center][/cell][cell padding=10,4,10,4][b]=[/b][/cell][cell bg=#classe_clair border=#classe padding=18,4,18,4][/cell][cell bg=#unites_clair border=#unites padding=18,4,18,4][center][b]5[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell bg=#dixiemes_clair border=#dixiemes padding=18,4,18,4][center][b]7[/b][/center][/cell][cell bg=#centiemes_clair border=#centiemes padding=18,4,18,4][center][b]9[/b][/center][/cell][/table]
Centièmes : 12 - 3 = 9. Dixièmes : 12 - 5 = 7. Unités : 10 - 5 = 5. Dizaines : 0.
[cadre][b]11,32 - 5,53 = 5,79[/b][/cadre]
[page]
[titre]La compensation, avec la virgule[/titre]
[table=6][cell padding=10,4,10,4][/cell][cell bg=#classe border=#classe padding=18,4,18,4][center][color=white][b]D[/b][/color][/center][/cell][cell bg=#unites border=#unites padding=18,4,18,4][center][color=white][b]U[/b][/color][/center][/cell][cell padding=6,4,6,4][/cell][cell bg=#dixiemes border=#dixiemes padding=18,4,18,4][center][color=white][b]1/10[/b][/color][/center][/cell][cell bg=#centiemes border=#centiemes padding=18,4,18,4][center][color=white][b]1/100[/b][/color][/center][/cell][cell padding=10,4,10,4][b][/b][/cell][cell border=#classe padding=18,4,18,4][center][b]1[/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b][color=#C62828][font_size=18]1[/font_size][/color]1[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b][color=#C62828][font_size=18]1[/font_size][/color]3[/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b][color=#C62828][font_size=18]1[/font_size][/color]2[/b][/center][/cell][cell padding=10,4,10,4][b]-[/b][/cell][cell border=#classe padding=18,4,18,4][center][b][color=#C62828][font_size=18]+1[/font_size][/color][/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b]5[color=#C62828][font_size=18]+1[/font_size][/color][/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b]5[color=#C62828][font_size=18]+1[/font_size][/color][/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b]3[/b][/center][/cell][cell padding=10,4,10,4][b]=[/b][/cell][cell bg=#classe_clair border=#classe padding=18,4,18,4][/cell][cell bg=#unites_clair border=#unites padding=18,4,18,4][center][b]5[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell bg=#dixiemes_clair border=#dixiemes padding=18,4,18,4][center][b]7[/b][/center][/cell][cell bg=#centiemes_clair border=#centiemes padding=18,4,18,4][center][b]9[/b][/center][/cell][/table]
À chaque colonne : 10 en haut, et 1 de plus en bas dans la colonne de gauche.
[cadre]12 - 3 = 9 · 13 - 6 = 7 · 11 - 6 = 5 · 1 - 1 = 0. Même résultat : [b]5,79[/b].
Utilise toujours [b]la méthode de ta classe[/b].[/cadre]
[page]
[titre]Soustraire d'un nombre entier[/titre]
Pour [b]25 - 7,36[/b], j'écris 25 avec une virgule et des 0 : [b]25,00[/b].
[table=6][cell padding=10,4,10,4][/cell][cell bg=#classe border=#classe padding=18,4,18,4][center][color=white][b]D[/b][/color][/center][/cell][cell bg=#unites border=#unites padding=18,4,18,4][center][color=white][b]U[/b][/color][/center][/cell][cell padding=6,4,6,4][/cell][cell bg=#dixiemes border=#dixiemes padding=18,4,18,4][center][color=white][b]1/10[/b][/color][/center][/cell][cell bg=#centiemes border=#centiemes padding=18,4,18,4][center][color=white][b]1/100[/b][/color][/center][/cell][cell padding=10,4,10,4][b][/b][/cell][cell border=#classe padding=18,4,18,4][center][b]2[/b][/center][/cell][cell border=#unites padding=18,4,18,4][center][b]5[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b][b][color=#C62828]0[/color][/b][/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b][b][color=#C62828]0[/color][/b][/b][/center][/cell][cell padding=10,4,10,4][b]-[/b][/cell][cell border=#classe padding=18,4,18,4][/cell][cell border=#unites padding=18,4,18,4][center][b]7[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b]3[/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b]6[/b][/center][/cell][cell padding=10,4,10,4][b]=[/b][/cell][cell bg=#classe_clair border=#classe padding=18,4,18,4][center][b]1[/b][/center][/cell][cell bg=#unites_clair border=#unites padding=18,4,18,4][center][b]7[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell bg=#dixiemes_clair border=#dixiemes padding=18,4,18,4][center][b]6[/b][/center][/cell][cell bg=#centiemes_clair border=#centiemes padding=18,4,18,4][center][b]4[/b][/center][/cell][/table]
[cadre]Puis je calcule avec la méthode de ma classe : [b]25 - 7,36 = 17,64[/b].[/cadre]
[page]
[titre]Le complément à 1[/titre]
Combien faut-il ajouter à [b]0,35[/b] pour avoir 1 ? 35 centièmes + 65 centièmes = 100 centièmes.
[table=3][cell bg=#classe_clair border=#classe padding=14,6,14,6][center][b]1 - 0,35 = 0,65[/b][/center][/cell][cell bg=#classe_clair border=#classe padding=14,6,14,6][center][b]1 - 0,8 = 0,2[/b][/center][/cell][cell bg=#classe_clair border=#classe padding=14,6,14,6][center][b]1 - 0,125 = 0,875[/b][/center][/cell][/table]
[cadre=astuce]Chiffre par chiffre, je complète à [b]9[/b], et le dernier chiffre à [b]10[/b] :
0,1[b]2[/b]5 → 1 + 8 = 9, 2 + 7 = 9, 5 + 5 = 10 → [b]0,875[/b].[/cadre]
[page]
[titre]Calculer de tête, malin[/titre]
[cadre]• Enlever [b]0,99[/b], c'est enlever 1 puis rajouter 0,01 : 8,45 - 0,99 = 7,45 + 0,01 = [b]7,46[/b].
• Enlever [b]0,9[/b], c'est enlever 1 puis rajouter 0,1 : 6,3 - 0,9 = 5,3 + 0,1 = [b]5,4[/b].[/cadre]
[cadre=astuce]J'ai enlevé un peu trop : je rends ce que j'ai pris en trop.[/cadre]
[page]
[titre]Vérifier avec une addition[/titre]
[table=6][cell padding=10,4,10,4][/cell][cell bg=#classe border=#classe padding=18,4,18,4][center][color=white][b]D[/b][/color][/center][/cell][cell bg=#unites border=#unites padding=18,4,18,4][center][color=white][b]U[/b][/color][/center][/cell][cell padding=6,4,6,4][/cell][cell bg=#dixiemes border=#dixiemes padding=18,4,18,4][center][color=white][b]1/10[/b][/color][/center][/cell][cell bg=#centiemes border=#centiemes padding=18,4,18,4][center][color=white][b]1/100[/b][/color][/center][/cell][cell padding=10,0,10,0][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]1[/b][/color][/font_size][/center][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]1[/b][/color][/font_size][/center][/cell][cell padding=6,0,6,0][/cell][cell padding=18,0,18,0][center][font_size=18][color=#C62828][b]1[/b][/color][/font_size][/center][/cell][cell padding=6,0,6,0][/cell][cell padding=10,4,10,4][b][/b][/cell][cell border=#classe padding=18,4,18,4][/cell][cell border=#unites padding=18,4,18,4][center][b]5[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b]7[/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b]9[/b][/center][/cell][cell padding=10,4,10,4][b]+[/b][/cell][cell border=#classe padding=18,4,18,4][/cell][cell border=#unites padding=18,4,18,4][center][b]5[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell border=#dixiemes padding=18,4,18,4][center][b]5[/b][/center][/cell][cell border=#centiemes padding=18,4,18,4][center][b]3[/b][/center][/cell][cell padding=10,4,10,4][b]=[/b][/cell][cell bg=#classe_clair border=#classe padding=18,4,18,4][center][b]1[/b][/center][/cell][cell bg=#unites_clair border=#unites padding=18,4,18,4][center][b]1[/b][/center][/cell][cell padding=6,4,6,4][center][b],[/b][/center][/cell][cell bg=#dixiemes_clair border=#dixiemes padding=18,4,18,4][center][b]3[/b][/center][/cell][cell bg=#centiemes_clair border=#centiemes padding=18,4,18,4][center][b]2[/b][/center][/cell][/table]
[cadre]5,79 + 5,53 = 11,32 : je retrouve le nombre du départ, ma soustraction est juste.[/cadre]
[page]
[titre]Je retiens[/titre]
[cadre]• Virgule sous virgule ; un entier s'écrit avec des 0 : 25 = 25,00.
• Pas assez ? Cassage ou compensation : [b]la méthode de ma classe[/b], dans chaque colonne.
• Complément à 1 : 1 - 0,35 = 0,65 (chiffres complétés à 9, le dernier à 10).
• - 0,99 = - 1 + 0,01.
• Je vérifie avec une addition.[/cadre]
$fiche$, 'publie', n.id from contenu_notions n where n.code = 'soustraction'
on conflict (notion_id, classe) where statut <> 'archive'
do update set titre = excluded.titre, contenu = excluded.contenu, statut = 'publie', modifie_le = now()
returning id, titre, statut;
select fn_publier();
