-- Fiche L'imparfait (CE2) - conjugaison, notion 'imparfait'. Relancer ce script remplace le contenu de la fiche.
insert into contenu_cours (classe, matiere, titre, contenu, statut, notion_id)
select 'ce2', 'conjugaison', 'L''imparfait', $fiche$
[titre]À quoi sert l'imparfait ?[/titre]
L'imparfait raconte ce qui se passait [b]avant[/b], ce qui [b]durait[/b] ou se [b]répétait[/b].
[cadre]Autrefois, mon grand-père [b]habitait[/b] à la campagne.
Chaque soir, il [b]rangeait[/b] ses outils.[/cadre]
[page]
[titre]Les terminaisons[/titre]
Pour [b]tous[/b] les verbes, les terminaisons sont les mêmes :
[table=3][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]parler[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]finir[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20][b]je[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]parl[b][color=#C62828]ais[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]finiss[b][color=#C62828]ais[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20][b]tu[/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20]parl[b][color=#C62828]ais[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20]finiss[b][color=#C62828]ais[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20][b]il, elle[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]parl[b][color=#C62828]ait[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]finiss[b][color=#C62828]ait[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20][b]nous[/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20]parl[b][color=#C62828]ions[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20]finiss[b][color=#C62828]ions[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20][b]vous[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]parl[b][color=#C62828]iez[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]finiss[b][color=#C62828]iez[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20][b]ils, elles[/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20]parl[b][color=#C62828]aient[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20]finiss[b][color=#C62828]aient[/color][/b][/font_size][/center][/cell][/table]
[cadre][b]ais, ais, ait, ions, iez, aient[/b][/cadre]
[page]
[titre]Trouver le radical[/titre]
Je prends le verbe au présent avec [b]nous[/b], j'enlève -ons, et j'ajoute la terminaison.
[cadre]nous parl[b]ons[/b] → je parl[b]ais[/b]
nous finiss[b]ons[/b] → je finiss[b]ais[/b]
nous fais[b]ons[/b] → je fais[b]ais[/b][/cadre]
[page]
[titre]Être et avoir[/titre]
[table=3][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]être[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]avoir[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20][b]je[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]j'ét[b][color=#C62828]ais[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]j'av[b][color=#C62828]ais[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20][b]tu[/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20]ét[b][color=#C62828]ais[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20]av[b][color=#C62828]ais[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20][b]il, elle[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]ét[b][color=#C62828]ait[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]av[b][color=#C62828]ait[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20][b]nous[/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20]ét[b][color=#C62828]ions[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20]av[b][color=#C62828]ions[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20][b]vous[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]ét[b][color=#C62828]iez[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]av[b][color=#C62828]iez[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20][b]ils, elles[/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20]ét[b][color=#C62828]aient[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=20]av[b][color=#C62828]aient[/color][/b][/font_size][/center][/cell][/table]
[cadre=astuce]Être est la seule exception : on dit « nous sommes » mais « j'[b]ét[/b]ais ».[/cadre]
[page]
[titre]-cer et -ger[/titre]
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]devant a : ç / ge[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]devant i : c / g[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]je lan[b][color=#C62828]ç[/color][/b]ais, il pla[b][color=#C62828]ç[/color][/b]ait[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]nous lan[b][color=#C62828]c[/color][/b]ions, vous pla[b][color=#C62828]c[/color][/b]iez[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]je plon[b][color=#C62828]ge[/color][/b]ais, ils ran[b][color=#C62828]ge[/color][/b]aient[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]nous plon[b][color=#C62828]g[/color][/b]ions, vous plon[b][color=#C62828]g[/color][/b]iez[/font_size][/center][/cell][/table]
[cadre=astuce]Devant [b]a[/b] : ç et ge. Devant [b]i[/b] : c et g suffisent.[/cadre]
[page]
[titre]Je retiens[/titre]
[cadre]• Imparfait : [b]ais, ais, ait, ions, iez, aient[/b] pour tous les verbes.
• Radical = présent avec nous, sans -ons : nous faisons → je faisais.
• Être : j'étais. Avoir : j'avais.
• je lançais, il plongeait ; nous lancions, nous plongions.[/cadre]
$fiche$, 'publie', n.id from contenu_notions n where n.code = 'imparfait'
on conflict (notion_id, classe) where statut <> 'archive'
do update set titre = excluded.titre, contenu = excluded.contenu, matiere = excluded.matiere, statut = 'publie', modifie_le = now()
returning id, classe, titre, statut;
