-- Fiche Le futur simple des verbes irréguliers (CM1) - conjugaison, notion 'futur'. Relancer ce script remplace le contenu de la fiche.
insert into contenu_cours (classe, matiere, titre, contenu, statut, notion_id)
select 'cm1', 'conjugaison', 'Le futur simple des verbes irréguliers', $fiche$
[titre]Rappel : les verbes réguliers[/titre]
Infinitif + [b]ai, as, a, ons, ez, ont[/b].
[table=3][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]chanter[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]finir[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]attendre[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]je chanter[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]je finir[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]j'attendr[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][/table]
[cadre=astuce]Verbes en -re : j'enlève le [b]e[/b] final : attendre → j'attendrai, vendre → je vendrai.[/cadre]
[page]
[titre]Des radicaux à connaître (1)[/titre]
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]être[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]je ser[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]avoir[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]j'aur[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]aller[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]j'ir[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]faire[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]je fer[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]venir[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]je viendr[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]tenir[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]je tiendr[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]voir[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]je verr[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]envoyer[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]j'enverr[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][/table]
[page]
[titre]Des radicaux à connaître (2)[/titre]
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]pouvoir[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]je pourr[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]vouloir[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]je voudr[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]devoir[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]je devr[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]savoir[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]je saur[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]courir[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]je courr[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]mourir[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]je mourr[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]prendre[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]je prendr[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]recevoir[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]je recevr[b][color=#C62828]ai[/color][/b][/font_size][/center][/cell][/table]
[page]
[titre]Les deux r[/titre]
[cadre]Avec [b]deux r[/b] : je cou[b]rr[/b]ai, je mou[b]rr[/b]ai, je pou[b]rr[/b]ai, je ve[b]rr[/b]ai, j'enve[b]rr[/b]ai.[/cadre]
[cadre=astuce]On entend bien le r prolongé : « je cour-rai ». À l'imparfait, un seul r : je courais.[/cadre]
[page]
[titre]Le radical change, pas les terminaisons[/titre]
[cadre]Même pour les verbes irréguliers, les terminaisons restent [b]ai, as, a, ons, ez, ont[/b] :
je ferai, tu feras, il fera, nous ferons, vous ferez, ils feront.[/cadre]
[page]
[titre]Je retiens[/titre]
[cadre]• Futur : radical + ai, as, a, ons, ez, ont.
• Radicaux spéciaux : ser-, aur-, ir-, fer-, viendr-, verr-, pourr-, voudr-, devr-, saur-.
• Deux r : courrai, mourrai, pourrai, verrai, enverrai.
• Verbes en -re : attendre → j'attendrai.[/cadre]
$fiche$, 'publie', n.id from contenu_notions n where n.code = 'futur'
on conflict (notion_id, classe) where statut <> 'archive'
do update set titre = excluded.titre, contenu = excluded.contenu, matiere = excluded.matiere, statut = 'publie', modifie_le = now()
returning id, classe, titre, statut;
