-- Fiche Le passé simple (CM2) - conjugaison, notion 'passe_simple'. Relancer ce script remplace le contenu de la fiche.
insert into contenu_cours (classe, matiere, titre, contenu, statut, notion_id)
select 'cm2', 'conjugaison', 'Le passé simple', $fiche$
[titre]Le temps des récits[/titre]
Le passé simple sert à raconter des [b]histoires[/b] et des faits passés, surtout à l'écrit.
[cadre]Le prince [b]monta[/b] sur son cheval et [b]partit[/b] au galop.[/cadre]
[cadre=astuce]On l'utilise surtout avec [b]il, elle, ils, elles[/b].[/cadre]
[page]
[titre]Les verbes en -er : a, èrent[/titre]
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]il, elle[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]ils, elles[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]il chant[b][color=#C62828]a[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]ils chant[b][color=#C62828]èrent[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=21]elle mange[b][color=#C62828]a[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=21]elles mang[b][color=#C62828]èrent[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]il all[b][color=#C62828]a[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]ils all[b][color=#C62828]èrent[/color][/b][/font_size][/center][/cell][/table]
[cadre=astuce]-ger : il mang[b]e[/b]a (on garde le e devant a).[/cadre]
[page]
[titre]it, irent[/titre]
Les verbes comme finir et beaucoup de verbes en -re :
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]il, elle[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]ils, elles[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]il fin[b][color=#C62828]it[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]ils fin[b][color=#C62828]irent[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]il rend[b][color=#C62828]it[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]ils rend[b][color=#C62828]irent[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]il f[b][color=#C62828]it[/color][/b] (faire)[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]ils f[b][color=#C62828]irent[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]il pr[b][color=#C62828]it[/color][/b] (prendre)[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]ils pr[b][color=#C62828]irent[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]il v[b][color=#C62828]it[/color][/b] (voir)[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]ils v[b][color=#C62828]irent[/color][/b][/font_size][/center][/cell][/table]
[page]
[titre]ut, urent[/titre]
Beaucoup de verbes en -oir et quelques autres :
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=18]avoir[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=18]il eut[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=18]être[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=18]il fut[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=18]pouvoir[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=18]il put[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=18]vouloir[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=18]il voulut[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=18]devoir[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=18]il dut[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=18]savoir[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=18]il sut[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=18]boire[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=18]il but[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=18]lire[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=18]il lut[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=18]croire[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=18]il crut[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=18]connaître[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=18]il connut[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=18]recevoir[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=18]il reçut[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=18]courir[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=18]il courut[/font_size][/center][/cell][/table]
[cadre]Avec ils : ils eurent, ils furent, ils purent…[/cadre]
[page]
[titre]venir et tenir : int, inrent[/titre]
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]il, elle[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]ils, elles[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]il v[b][color=#C62828]int[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]ils v[b][color=#C62828]inrent[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=22]il t[b][color=#C62828]int[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=22]ils t[b][color=#C62828]inrent[/color][/b][/font_size][/center][/cell][/table]
[cadre=astuce]Pas d'accent : il vint, ils vinrent.[/cadre]
[page]
[titre]Les pièges[/titre]
[cadre]• il regard[b]a[/b] (passé simple) ≠ il regard[b]ait[/b] (imparfait)
• il entend[b]it[/b] avec [b]t[/b] (pas « il entendis »)
• ils pass[b]èrent[/b] avec un accent grave[/cadre]
[page]
[titre]Je retiens[/titre]
[cadre]• -er : il chanta, ils chantèrent.
• finir, rendre, faire, prendre, voir : il finit, ils finirent.
• avoir, être, pouvoir, vouloir… : il eut, il fut, il put, ils purent.
• venir, tenir : il vint, ils vinrent.[/cadre]
$fiche$, 'publie', n.id from contenu_notions n where n.code = 'passe_simple'
on conflict (notion_id, classe) where statut <> 'archive'
do update set titre = excluded.titre, contenu = excluded.contenu, matiere = excluded.matiere, statut = 'publie', modifie_le = now()
returning id, classe, titre, statut;
