-- Fiche Écrire les nombres en lettres (CP) - francais, notion 'nombres_en_lettres'. Relancer ce script remplace le contenu de la fiche.
insert into contenu_cours (classe, matiere, titre, contenu, statut, notion_id)
select 'cp', 'french', 'Écrire les nombres en lettres', $fiche$
[titre]De zéro à dix[/titre]
Chaque nombre a un [b]nom[/b] qu'on peut écrire en lettres.
[table=6][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21][b]0[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]zéro[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21][b]1[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21]un[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21][b]2[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]deux[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21][b]3[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21]trois[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21][b]4[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]quatre[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21][b]5[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21]cinq[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21][b]6[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]six[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21][b]7[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21]sept[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21][b]8[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]huit[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21][b]9[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21]neuf[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21][b]10[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]dix[/font_size][/center][/cell][/table]
[cadre=astuce]Attention : [b]cinq[/b] finit par q, [b]sept[/b] a un p qui ne s'entend pas.[/cadre]
[page]
[titre]De onze à seize[/titre]
Ces nombres ont un nom [b]à eux[/b]. Il faut les apprendre par cœur.
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22][b]11[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]onze[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22][b]12[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]douze[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22][b]13[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]treize[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22][b]14[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]quatorze[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22][b]15[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]quinze[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22][b]16[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]seize[/font_size][/center][/cell][/table]
[cadre]On ne dit pas « dix-un », mais [b]onze[/b] !
On ne dit pas « dix-cinq », mais [b]quinze[/b] ![/cadre]
[page]
[titre]Dix-sept, dix-huit, dix-neuf[/titre]
À partir de 17, on dit [b]dix[/b], puis le chiffre des unités.
[table=2][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=24][b]17[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=24]dix-sept[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=24][b]18[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=24]dix-huit[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=24][b]19[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=24]dix-neuf[/font_size][/center][/cell][/table]
[cadre]dix-sept = [b]10 + 7[/b]. Entre les deux mots, je mets un [b]trait d'union[/b] (-).[/cadre]
[page]
[titre]Les dizaines[/titre]
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22][b]10[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]dix[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22][b]20[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]vingt[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22][b]30[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]trente[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22][b]40[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]quarante[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22][b]50[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]cinquante[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22][b]60[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]soixante[/font_size][/center][/cell][/table]
[cadre=astuce][b]vingt[/b] s'écrit avec un g et un t qu'on n'entend pas : v-i-n-g-t.[/cadre]
[page]
[titre]Fabriquer un nombre[/titre]
Pour 26, je dis la [b]dizaine[/b], puis l'[b]unité[/b] : 20 et 6.
[cubes d=2 u=6]
[center][font_size=30][b]26 → vingt[b][color=#C62828]-[/color][/b]six[/b][/font_size][/center]
[cadre]Entre les mots d'un nombre, je mets des [b]traits d'union[/b] : trente-quatre, cinquante-deux.[/cadre]
[page]
[titre]Le « et un »[/titre]
Avec un [b]1[/b] aux unités, on ajoute [b]et[/b] :
[table=2][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22][b]21[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]vingt-et-un[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22][b]31[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]trente-et-un[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22][b]41[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]quarante-et-un[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22][b]51[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]cinquante-et-un[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22][b]61[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]soixante-et-un[/font_size][/center][/cell][/table]
[cadre]On ne dit pas « vingt-un », mais [b]vingt-et-un[/b].
Les traits d'union vont partout : vingt[b]-[/b]et[b]-[/b]un.[/cadre]
[page]
[titre]De 70 à 79[/titre]
70, c'est [b]60 + 10[/b] : on dit [b]soixante-dix[/b].
Puis on continue avec onze, douze, treize…
[table=2][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22][b]70[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]soixante-dix[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22][b]71[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]soixante-et-onze[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22][b]72[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]soixante-douze[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22][b]75[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]soixante-quinze[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22][b]79[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]soixante-dix-neuf[/font_size][/center][/cell][/table]
[cadre]soixante-quinze = [b]60 + 15[/b] = 75.[/cadre]
[page]
[titre]De 80 à 100[/titre]
80, c'est [b]4 fois 20[/b] : on dit [b]quatre-vingts[/b].
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20][b]80[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]quatre-vingts[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20][b]81[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]quatre-vingt-un[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20][b]85[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]quatre-vingt-cinq[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20][b]90[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]quatre-vingt-dix[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20][b]91[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]quatre-vingt-onze[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20][b]95[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]quatre-vingt-quinze[/font_size][/center][/cell][/table]
[cadre=astuce][b]quatre-vingts[/b] prend un s, mais pas quatre-vingt-un.
81 : pas de « et » → quatre-vingt-un. Et 100 s'écrit [b]cent[/b].[/cadre]
[page]
[titre]Lire un nombre écrit en lettres[/titre]
Je découpe le nombre en morceaux, puis j'additionne.
[table=3][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]vingt-neuf[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]20 + 9[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21][b]29[/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21]soixante-quinze[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21]60 + 15[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21][b]75[/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]quatre-vingt-onze[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]80 + 11[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21][b]91[/b][/font_size][/center][/cell][/table]
[cadre=astuce]quatre-vingt-onze : « quatre-vingt » = 80 et « onze » = 11. 80 + 11 = [b]91[/b].[/cadre]
[page]
[titre]Je retiens[/titre]
[cadre]• 11 à 16 ont un nom à eux : onze, douze, treize, quatorze, quinze, seize.
• 17, 18, 19 : dix-sept, dix-huit, dix-neuf.
• Dizaine + unité avec un [b]trait d'union[/b] : vingt-six.
• Avec 1 : vingt-[b]et[/b]-un (mais quatre-vingt-un).
• 70 = soixante-dix, 80 = quatre-vingt[b]s[/b], 90 = quatre-vingt-dix.[/cadre]
$fiche$, 'publie', n.id from contenu_notions n where n.code = 'nombres_en_lettres'
on conflict (notion_id, classe) where statut <> 'archive'
do update set titre = excluded.titre, contenu = excluded.contenu, matiere = excluded.matiere, statut = 'publie', modifie_le = now()
returning id, classe, titre, statut;
