-- Fiche Vocabulaire du quotidien (CP) - francais, notion 'vocabulaire_quotidien'. Relancer ce script remplace le contenu de la fiche.
insert into contenu_cours (classe, matiere, titre, contenu, statut, notion_id)
select 'cp', 'french', 'Vocabulaire du quotidien', $fiche$
[titre]Les couleurs (1)[/titre]
[table=3][cell bg=#E53935 border=#classe padding=22,4,22,4] [/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][b]rouge[/b][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4]fraise, cerise, tomate[/cell][cell bg=#FDD835 border=#classe padding=22,4,22,4] [/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][b]jaune[/b][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4]banane, citron, poussin[/cell][cell bg=#43A047 border=#classe padding=22,4,22,4] [/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][b]vert[/b][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4]herbe, sapin, brocoli[/cell][cell bg=#1E88E5 border=#classe padding=22,4,22,4] [/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][b]bleu[/b][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4]ciel, mer, myrtille[/cell][cell bg=#FB8C00 border=#classe padding=22,4,22,4] [/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][b]orange[/b][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4]carotte, citrouille[/cell][/table]
[page]
[titre]Les couleurs (2)[/titre]
[table=3][cell bg=#8E24AA border=#classe padding=22,4,22,4] [/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][b]violet[/b][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4]aubergine, prune[/cell][cell bg=#F48FB1 border=#classe padding=22,4,22,4] [/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][b]rose[/b][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4]flamant rose[/cell][cell bg=#8D5524 border=#classe padding=22,4,22,4] [/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][b]marron[/b][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4]chocolat, café[/cell][cell bg=#9E9E9E border=#classe padding=22,4,22,4] [/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][b]gris[/b][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4]éléphant, fumée[/cell][cell bg=#212121 border=#classe padding=22,4,22,4] [/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][b]noir[/b][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4]charbon, corbeau[/cell][cell bg=#FFFFFF border=#classe padding=22,4,22,4] [/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][b]blanc[/b][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4]neige, lait, nuage[/cell][/table]
[cadre]Le zèbre, le panda et le pingouin sont [b]noir et blanc[/b].[/cadre]
[page]
[titre]Les jours de la semaine[/titre]
Une semaine a [b]7 jours[/b], toujours dans le même ordre :
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]1. lundi[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]2. mardi[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]3. mercredi[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]4. jeudi[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]5. vendredi[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]6. samedi[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]7. dimanche[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22] [/font_size][/center][/cell][/table]
[cadre]Le [b]premier[/b] jour est [b]lundi[/b]. Le [b]dernier[/b] est [b]dimanche[/b].
Après dimanche, une nouvelle semaine recommence : [b]lundi[/b].[/cadre]
[page]
[titre]Avant, après[/titre]
[table=3][cell bg=#classe_clair border=#classe padding=12,6,12,6][center][font_size=24][b]mardi[/b][/font_size][/center][/cell][cell bg=#unites border=#unites padding=12,6,12,6][center][font_size=24][b][color=white]mercredi[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=12,6,12,6][center][font_size=24][b]jeudi[/b][/font_size][/center][/cell][/table]
[cadre]Juste [b]avant[/b] mercredi, c'est [b]mardi[/b].
Juste [b]après[/b] mercredi, c'est [b]jeudi[/b].[/cadre]
[cadre=astuce]Je récite les jours depuis lundi, et je m'arrête au bon jour. Avant = à gauche, après = à droite.[/cadre]
[page]
[titre]Les 12 mois de l'année[/titre]
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]janvier[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]février[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]mars[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]avril[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]mai[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]juin[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]juillet[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]août[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]septembre[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]octobre[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]novembre[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]décembre[/font_size][/center][/cell][/table]
[cadre]Une année a [b]12 mois[/b]. Elle commence en [b]janvier[/b] et finit en [b]décembre[/b].
Après décembre, on recommence : [b]janvier[/b].[/cadre]
[page]
[titre]Les bébés des animaux (1)[/titre]
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🐱 le chat[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]le chaton[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🐶 le chien[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]le chiot[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🐮 la vache[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]le veau[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🐴 le cheval[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]le poulain[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🐑 le mouton[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]l'agneau[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🐐 la chèvre[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]le chevreau[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🐔 la poule[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]le poussin[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🐸 la grenouille[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]le têtard[/font_size][/center][/cell][/table]
[page]
[titre]Les bébés des animaux (2)[/titre]
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🦁 le lion[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]le lionceau[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🐻 l'ours[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]l'ourson[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🐰 le lapin[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]le lapereau[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🦊 le renard[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]le renardeau[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🐺 le loup[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]le louveteau[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🐭 la souris[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]le souriceau[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🦆 le canard[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]le caneton[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🐦 l'oiseau[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]l'oisillon[/font_size][/center][/cell][/table]
[cadre=astuce]On entend souvent le nom de l'animal : [b]renard[/b] → [b]renard[/b]eau, [b]éléphant[/b] → [b]éléphant[/b]eau, [b]pigeon[/b] → [b]pigeon[/b]neau, [b]cygne[/b] → [b]cygne[/b]au, [b]oie[/b] → [b]oi[/b]son.[/cadre]
[page]
[titre]Je retiens[/titre]
[cadre]• Je sais nommer les [b]couleurs[/b] des choses que je vois tous les jours.
• 7 jours : lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche.
• 12 mois : de [b]janvier[/b] à [b]décembre[/b].
• Chaque animal a son [b]bébé[/b] : le chat → le chaton, le lion → le lionceau.[/cadre]
$fiche$, 'publie', n.id from contenu_notions n where n.code = 'vocabulaire_quotidien'
on conflict (notion_id, classe) where statut <> 'archive'
do update set titre = excluded.titre, contenu = excluded.contenu, matiere = excluded.matiere, statut = 'publie', modifie_le = now()
returning id, classe, titre, statut;
