-- Fiche Masculin et féminin (CP) - francais, notion 'masculin_feminin'. Relancer ce script remplace le contenu de la fiche.
insert into contenu_cours (classe, matiere, titre, contenu, statut, notion_id)
select 'cp', 'french', 'Masculin et féminin', $fiche$
[titre]Un ou une ?[/titre]
Les noms sont [b]masculins[/b] ou [b]féminins[/b]. Le petit mot devant me le dit.
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]masculin[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]féminin[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=24]le, un[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=24]la, une[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=24]le garçon[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=24]la fille[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=24]un papa[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=24]une maman[/font_size][/center][/cell][/table]
[cadre]Je dis « [b]un[/b] » ou « [b]une[/b] » devant le nom pour savoir.[/cadre]
[page]
[titre]Le mâle et la femelle[/titre]
Chez les animaux, le [b]mâle[/b] est au masculin, la [b]femelle[/b] au féminin.
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]le mâle[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]la femelle[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]🐰 un lapin[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]une lapin[b][color=#C62828]e[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]🦊 un renard[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]une renard[b][color=#C62828]e[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]🐻 un ours[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]une ours[b][color=#C62828]e[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]🐘 un éléphant[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]une éléphant[b][color=#C62828]e[/color][/b][/font_size][/center][/cell][/table]
[cadre]Souvent, j'ajoute simplement un [b]e[/b] à la fin.[/cadre]
[page]
[titre]J'ajoute une lettre en plus[/titre]
Parfois, la dernière lettre est [b]doublée[/b] avant le e.
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]le mâle[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]la femelle[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]🐱 un chat[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]une chat[b][color=#C62828]te[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]🐶 un chien[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]une chien[b][color=#C62828]ne[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]🦁 un lion[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]une lion[b][color=#C62828]ne[/color][/b][/font_size][/center][/cell][/table]
D'autres fois, la fin change davantage :
[table=2][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]🐺 un lou[b][color=#C62828]p[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]une lou[b][color=#C62828]ve[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]🐯 un tigre[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]une tigr[b][color=#C62828]esse[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]🫏 un âne[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]une ân[b][color=#C62828]esse[/color][/b][/font_size][/center][/cell][/table]
[page]
[titre]Des noms tout différents[/titre]
Pour certains animaux, la femelle a un [b]autre nom[/b]. Il faut les apprendre.
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🐓 le coq[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]la poule[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🐑 le mouton[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]la brebis[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🐴 le cheval[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]la jument[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🦌 le cerf[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]la biche[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🐂 le taureau[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]la vache[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🐐 le bouc[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]la chèvre[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🐷 le cochon[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]la truie[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🐒 le singe[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]la guenon[/font_size][/center][/cell][/table]
[page]
[titre]D'autres noms à connaître[/titre]
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🐗 le sanglier[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]la laie[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🪿 le jars[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]l'oie[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🐮 le bœuf[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]la vache[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🦆 le canard[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]la cane[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]🦃 le dindon[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]la dinde[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]🦚 le paon[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]la paonne[/font_size][/center][/cell][/table]
[cadre=astuce]Attention : la vache est la femelle du [b]taureau[/b] et du [b]bœuf[/b].
La femelle du canard est la [b]cane[/b] : un seul n.[/cadre]
[page]
[titre]Les personnes aussi[/titre]
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]masculin[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]féminin[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=24]un prince[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=24]une princ[b][color=#C62828]esse[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=24]un ami[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=24]une ami[b][color=#C62828]e[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=24]un roi[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=24]une reine[/font_size][/center][/cell][/table]
[cadre]Les mêmes règles marchent : j'ajoute un e, ou la fin change, ou le mot change complètement.[/cadre]
[page]
[titre]Du féminin au masculin[/titre]
On me donne la femelle, je cherche le mâle : je fais le chemin [b]à l'envers[/b].
[cadre]une lapin[b]e[/b] → j'enlève le e → un [b]lapin[/b]
une lou[b]ve[/b] → un [b]loup[/b]
une brebis → un [b]mouton[/b] (nom différent)[/cadre]
[cadre=astuce]Je dis « [b]un[/b] » devant ma réponse pour vérifier qu'elle sonne juste.[/cadre]
[page]
[titre]Je retiens[/titre]
[cadre]• le, un → [b]masculin[/b]. la, une → [b]féminin[/b].
• Souvent, j'ajoute un [b]e[/b] : un renard, une renarde.
• Parfois, la lettre est doublée : chat → chatte, chien → chienne.
• Parfois, la fin change : loup → louve, tigre → tigresse.
• Parfois, le nom change : coq → poule, cheval → jument.[/cadre]
$fiche$, 'publie', n.id from contenu_notions n where n.code = 'masculin_feminin'
on conflict (notion_id, classe) where statut <> 'archive'
do update set titre = excluded.titre, contenu = excluded.contenu, matiere = excluded.matiere, statut = 'publie', modifie_le = now()
returning id, classe, titre, statut;
