-- Fiche Le pluriel des noms (CE1) - grammaire, notion 'singulier_pluriel'. Relancer ce script remplace le contenu de la fiche.
insert into contenu_cours (classe, matiere, titre, contenu, statut, notion_id)
select 'ce1', 'grammaire', 'Le pluriel des noms', $fiche$
[titre]Singulier et pluriel[/titre]
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]singulier : un seul[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]pluriel : plusieurs[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]un robot[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]des robot[b][color=#C62828]s[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21]une trousse[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=21]des trousse[b][color=#C62828]s[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]un canapé[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=21]des canapé[b][color=#C62828]s[/color][/b][/font_size][/center][/cell][/table]
[cadre]En général, au pluriel, j'ajoute un [b]s[/b]. Il ne s'entend pas.[/cadre]
[page]
[titre]-eau → x[/titre]
Les noms en [b]-eau[/b] prennent un [b]x[/b] au pluriel.
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un drapeau[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des drapeau[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]un morceau[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]des morceau[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]un panneau[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]des panneau[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un roseau[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des roseau[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un réseau[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des réseau[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]un niveau[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]des niveau[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][/table]
[page]
[titre]-al → -aux[/titre]
Les noms en [b]-al[/b] deviennent [b]-aux[/b].
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un chev[b][color=#C62828]al[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des chev[b][color=#C62828]aux[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]un journ[b][color=#C62828]al[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]des journ[b][color=#C62828]aux[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]un hôpit[b][color=#C62828]al[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]des hôpit[b][color=#C62828]aux[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un can[b][color=#C62828]al[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des can[b][color=#C62828]aux[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un boc[b][color=#C62828]al[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des boc[b][color=#C62828]aux[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]un m[b][color=#C62828]al[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]des m[b][color=#C62828]aux[/color][/b][/font_size][/center][/cell][/table]
[page]
[titre]Quelques mots en -ail → -aux[/titre]
La plupart des noms en -ail prennent un s : un éventail → des éventail[b][color=#C62828]s[/color][/b].
Mais quelques-uns deviennent [b]-aux[/b] :
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]singulier[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]pluriel[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]un trav[b][color=#C62828]ail[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]des trav[b][color=#C62828]aux[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]un cor[b][color=#C62828]ail[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]des cor[b][color=#C62828]aux[/color][/b][/font_size][/center][/cell][/table]
[page]
[titre]Les noms qui ne changent pas[/titre]
Un nom qui finit déjà par [b]s[/b], [b]x[/b] ou [b]z[/b] reste pareil au pluriel.
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un radis[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des radis[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]un repas[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]des repas[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]une voix[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]des voix[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un prix[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des prix[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un nez[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des nez[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]un gaz[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=19]des gaz[/font_size][/center][/cell][/table]
[cadre=astuce]C'est le petit mot devant (un / des) qui montre le pluriel.[/cadre]
[page]
[titre]Je retiens[/titre]
[cadre]• En général : [b]+ s[/b] (un robot, des robots).
• -eau → [b]x[/b] : des drapeaux.
• -al → [b]-aux[/b] : des chevaux. Aussi : travail → travaux, corail → coraux.
• Déjà fini par s, x, z : [b]pas de changement[/b].[/cadre]
$fiche$, 'publie', n.id from contenu_notions n where n.code = 'singulier_pluriel'
on conflict (notion_id, classe) where statut <> 'archive'
do update set titre = excluded.titre, contenu = excluded.contenu, matiere = excluded.matiere, statut = 'publie', modifie_le = now()
returning id, classe, titre, statut;
