-- Fiche Masculin et féminin des animaux (CE1) - orthographe, notion 'masculin_feminin'. Relancer ce script remplace le contenu de la fiche.
insert into contenu_cours (classe, matiere, titre, contenu, statut, notion_id)
select 'ce1', 'orthographe', 'Masculin et féminin des animaux', $fiche$
[titre]Le mâle et la femelle[/titre]
Chez les animaux, le [b]mâle[/b] est au masculin (le, un), la [b]femelle[/b] au féminin (la, une).
Souvent, j'ajoute simplement un [b]e[/b] :
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]le lapin[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]la lapin[b][color=#C62828]e[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]le renard[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]la renard[b][color=#C62828]e[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]l'ours[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]l'ours[b][color=#C62828]e[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]le faisan[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]la faisan[b][color=#C62828]e[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]l'éléphant[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]l'éléphant[b][color=#C62828]e[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20] [/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20] [/font_size][/center][/cell][/table]
[page]
[titre]Je double la consonne[/titre]
Avec certaines fins, je [b]double[/b] la dernière consonne avant le e.
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]mâle[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]femelle[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]le chat[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]la cha[b][color=#C62828]tte[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]le chien[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]la chie[b][color=#C62828]nne[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]le lion[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]la lio[b][color=#C62828]nne[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]le paon[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]la pao[b][color=#C62828]nne[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]le pigeon[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]la pigeo[b][color=#C62828]nne[/color][/b][/font_size][/center][/cell][/table]
[cadre=astuce]-on → -[b]onne[/b], -ien → -[b]ienne[/b].[/cadre]
[page]
[titre]La fin change[/titre]
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]mâle[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]femelle[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]le lou[b][color=#C62828]p[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]la lou[b][color=#C62828]ve[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]l'âne[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]l'ân[b][color=#C62828]esse[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]le tigre[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]la tigr[b][color=#C62828]esse[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]le chame[b][color=#C62828]au[/color][/b][/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=22]la chame[b][color=#C62828]lle[/color][/b][/font_size][/center][/cell][/table]
[cadre]Le chameau et la chamelle : [b]-eau[/b] devient [b]-elle[/b], comme un beau / une belle.[/cadre]
[page]
[titre]Des noms différents (1)[/titre]
Pour beaucoup d'animaux de la ferme, la femelle a un [b]autre nom[/b] :
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]le coq[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]la poule[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]le cheval[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]la jument[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]le taureau[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]la vache[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]le bouc[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]la chèvre[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]le bélier[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]la brebis[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]le cochon[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]la truie[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]le dindon[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]la dinde[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]le canard[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]la cane[/font_size][/center][/cell][/table]
[cadre=astuce]Le mâle de la brebis s'appelle le [b]bélier[/b]. Le mot « mouton » sert pour tout le troupeau.[/cadre]
[page]
[titre]Des noms différents (2)[/titre]
Et pour les animaux sauvages :
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]le cerf[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]la biche[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]le sanglier[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]la laie[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]le lièvre[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20]la hase[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]le singe[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]la guenon[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]le jars[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=20]l'oie[/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20] [/font_size][/center][/cell][cell bg=#FFD49A border=#F2A541 padding=10,4,10,4][center][font_size=20] [/font_size][/center][/cell][/table]
[cadre]Ces noms ne se devinent pas : il faut les [b]apprendre[/b].[/cadre]
[page]
[titre]Trouver le mâle[/titre]
On me donne la femelle, je cherche le mâle : je fais le chemin [b]à l'envers[/b].
[cadre]la lapin[b]e[/b] → j'enlève le e → le [b]lapin[/b]
la lio[b]nne[/b] → j'enlève -ne → le [b]lion[/b]
la lou[b]ve[/b] → le [b]loup[/b] (pas « louv » !)
la hase → le [b]lièvre[/b] (nom différent)[/cadre]
[cadre=astuce]Je dis « le » devant ma réponse : « le loup » sonne juste ✓[/cadre]
[page]
[titre]Je retiens[/titre]
[cadre]• Souvent, j'ajoute un [b]e[/b] : le renard, la renarde.
• -on, -ien : je double le n → lionne, chienne, pigeonne.
• Parfois, la fin change : loup → louve, âne → ânesse, chameau → chamelle.
• Parfois, le nom change : bélier → brebis, lièvre → hase, jars → oie.
• Pour trouver le mâle, je fais le chemin à l'envers.[/cadre]
$fiche$, 'publie', n.id from contenu_notions n where n.code = 'masculin_feminin'
on conflict (notion_id, classe) where statut <> 'archive'
do update set titre = excluded.titre, contenu = excluded.contenu, matiere = excluded.matiere, statut = 'publie', modifie_le = now()
returning id, classe, titre, statut;
