-- Fiche Le pluriel des noms (CE2) - orthographe, notion 'singulier_pluriel'. Relancer ce script remplace le contenu de la fiche.
insert into contenu_cours (classe, matiere, titre, contenu, statut, notion_id)
select 'ce2', 'orthographe', 'Le pluriel des noms', $fiche$
[titre]Rappel : j'ajoute un s[/titre]
En général, au pluriel, j'ajoute un [b]s[/b] qui ne s'entend pas.
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]singulier[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]pluriel[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]un ballon[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]des ballon[b][color=#C62828]s[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=22]une porte[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=22]des porte[b][color=#C62828]s[/color][/b][/font_size][/center][/cell][/table]
[cadre]Mais certaines fins de mots prennent un [b]x[/b]. Il faut bien regarder la fin du mot ![/cadre]
[page]
[titre]-eau et -au → x[/titre]
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un bateau[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des bateau[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]un chapeau[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]des chapeau[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]un ruisseau[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]des ruisseau[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un tuyau[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des tuyau[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un noyau[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des noyau[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]un préau[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]des préau[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][/table]
[cadre=astuce]Une exception : un landau → des landau[b]s[/b].[/cadre]
[page]
[titre]-eu → x[/titre]
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un feu[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des feu[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]un jeu[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]des jeu[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]un cheveu[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]des cheveu[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un neveu[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des neveu[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]un lieu[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=19]des lieu[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]un vœu[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=19]des vœu[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][/table]
[cadre=astuce]Exceptions : un pneu → des pneu[b]s[/b], bleu → bleu[b]s[/b].[/cadre]
[page]
[titre]-ou : s, sauf 7 mots[/titre]
Les mots en -ou prennent un [b]s[/b] : un trou → des trou[b][color=#C62828]s[/color][/b], un clou → des clou[b][color=#C62828]s[/color][/b].
Sauf [b]7 mots[/b] qui prennent un [b]x[/b] :
[table=4][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]bijou[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]caillou[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]chou[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]genou[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]hibou[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]joujou[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]pou[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22] [/font_size][/center][/cell][/table]
[cadre]« Viens, mon chou, mon bijou, sur mes genoux, avec tes joujoux, et jette des cailloux à ce hibou plein de poux ! »[/cadre]
[page]
[titre]-al → -aux[/titre]
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]singulier[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]pluriel[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]un chev[b][color=#C62828]al[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]des chev[b][color=#C62828]aux[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=22]un journ[b][color=#C62828]al[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=22]des journ[b][color=#C62828]aux[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]un anim[b][color=#C62828]al[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]des anim[b][color=#C62828]aux[/color][/b][/font_size][/center][/cell][/table]
[cadre=astuce]Exceptions : un bal, un carnaval, un festival → des bal[b]s[/b], des carnaval[b]s[/b], des festival[b]s[/b].[/cadre]
[page]
[titre]Les noms qui ne changent pas[/titre]
Un nom qui finit déjà par [b]s[/b], [b]x[/b] ou [b]z[/b] ne change pas au pluriel.
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]singulier[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]pluriel[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]une souris[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]des souris[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=22]un prix[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=22]des prix[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]un nez[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]des nez[/font_size][/center][/cell][/table]
[page]
[titre]Retrouver le singulier[/titre]
Je fais le chemin [b]à l'envers[/b] : j'enlève le s ou le x.
[table=2][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]pluriel[/b][/color][/center][/cell][cell bg=#classe border=#classe padding=10,4,10,4][center][color=white][b]singulier[/b][/color][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]des panneau[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]un panneau[/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=22]des pou[b][color=#C62828]x[/color][/b][/font_size][/center][/cell][cell bg=#C6E2F8 border=#42A5F5 padding=10,4,10,4][center][font_size=22]un pou[/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]des chev[b][color=#C62828]aux[/color][/b][/font_size][/center][/cell][cell bg=#classe_clair border=#classe padding=10,4,10,4][center][font_size=22]un chev[b][color=#C62828]al[/color][/b][/font_size][/center][/cell][/table]
[cadre=astuce]chevaux → cheval, pas « chevau » ! Je dis « un » devant pour vérifier.[/cadre]
[page]
[titre]Je retiens[/titre]
[cadre]• En général : [b]+ s[/b].
• -eau, -au, -eu → [b]x[/b] (sauf landaus, pneus, bleus).
• -ou → s, sauf les 7 mots en [b]x[/b] : bijou, caillou, chou, genou, hibou, joujou, pou.
• -al → [b]-aux[/b] (sauf bals, carnavals, festivals).
• Déjà fini par s, x, z : [b]pas de changement[/b].[/cadre]
$fiche$, 'publie', n.id from contenu_notions n where n.code = 'singulier_pluriel'
on conflict (notion_id, classe) where statut <> 'archive'
do update set titre = excluded.titre, contenu = excluded.contenu, matiere = excluded.matiere, statut = 'publie', modifie_le = now()
returning id, classe, titre, statut;
