-- ============================================================================
-- Contenu pédagogique (questions, textes de lecture, cours) dans Supabase.
-- Créé le 2026-09-26 (phase 1 de la migration CSV -> Supabase, voir mémoire projet
-- project_contenu_supabase_migration).
--
-- SANS DANGER pour les comptes joueurs : ce fichier ne touche à AUCUNE table existante
-- (comptes, progressions, sessions...), il n'y a aucun DROP. Toutes les tables créées ici
-- commencent par "contenu_".
--
-- Principe :
--   * contenu_questions / contenu_passages / contenu_cours = l'atelier (on y écrit, on corrige,
--     statut brouillon/publie/archive). Le jeu ne les lit JAMAIS directement.
--   * fn_publier() vérifie tout, puis fige une photo par classe+matière dans contenu_paquets.
--   * Le jeu lit uniquement fn_manifeste() (versions) et fn_paquet(classe, matiere) (contenu).
--   * contenu_historique garde automatiquement l'ancienne version de toute ligne modifiée/supprimée.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. Petite fonction utilitaire : vrai si une liste ne contient aucun doublon.
--    (Une contrainte CHECK ne peut pas contenir de sous-requête, d'où cette fonction.)
-- ---------------------------------------------------------------------------
create or replace function fn_sans_doublon(p_liste text[])
returns boolean
language sql
immutable
as $$
	select count(*) = count(distinct x) from unnest(p_liste) as x;
$$;

-- ---------------------------------------------------------------------------
-- 1. Cours (créé en premier : les questions y font référence)
--    contenu = texte au format BBCode de Godot (gras, couleurs, listes, tableaux), sans image.
-- ---------------------------------------------------------------------------
create table if not exists contenu_cours (
	id integer primary key generated by default as identity,
	classe text not null check (classe in ('cp', 'ce1', 'ce2', 'cm1', 'cm2')),
	matiere text not null check (matiere in ('math', 'french', 'grammaire', 'conjugaison', 'orthographe', 'english', 'lecture', 'logique')),
	titre text not null check (length(trim(titre)) > 0),
	contenu text not null check (length(trim(contenu)) > 0),
	statut text not null default 'brouillon' check (statut in ('brouillon', 'publie', 'archive')),
	cree_le timestamptz not null default now(),
	modifie_le timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 2. Textes de lecture
-- ---------------------------------------------------------------------------
create table if not exists contenu_passages (
	id integer primary key generated by default as identity,
	classe text not null check (classe in ('cp', 'ce1', 'ce2', 'cm1', 'cm2')),
	texte text not null check (length(trim(texte)) > 0),
	statut text not null default 'brouillon' check (statut in ('brouillon', 'publie', 'archive')),
	cree_le timestamptz not null default now(),
	modifie_le timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 3. Questions
--    Les id des CSV sont repris tels quels à la migration ; les nouvelles questions
--    partiront au-dessus du plus grand id existant (voir le setval du script de migration).
-- ---------------------------------------------------------------------------
create table if not exists contenu_questions (
	id integer primary key generated by default as identity,
	classe text not null check (classe in ('cp', 'ce1', 'ce2', 'cm1', 'cm2')),
	matiere text not null check (matiere in ('math', 'french', 'grammaire', 'conjugaison', 'orthographe', 'english', 'lecture', 'logique')),
	enonce text not null check (length(trim(enonce)) > 0),
	bonne_reponse text not null check (length(trim(bonne_reponse)) > 0),
	mauvais_choix text[] not null,
	grille text[],
	passage_id integer references contenu_passages (id),
	type_lecture text check (type_lecture in ('L', 'I', 'V')),
	cours_id integer references contenu_cours (id),
	statut text not null default 'brouillon' check (statut in ('brouillon', 'publie', 'archive')),
	cree_le timestamptz not null default now(),
	modifie_le timestamptz not null default now(),

	-- 1 à 3 mauvais choix, sans doublon, jamais égaux à la bonne réponse
	constraint q_nb_choix check (cardinality(mauvais_choix) between 1 and 3),
	constraint q_choix_sans_doublon check (fn_sans_doublon(mauvais_choix)),
	constraint q_bonne_reponse_hors_choix check (not (bonne_reponse = any (mauvais_choix))),
	-- lecture <=> rattachée à un texte ; type L/I/V seulement pour la lecture
	constraint q_lecture_passage check ((matiere = 'lecture') = (passage_id is not null)),
	constraint q_type_lecture check (type_lecture is null or matiere = 'lecture'),
	-- grille 3x3 = exactement 9 cases, seulement en logique
	constraint q_grille check (grille is null or (cardinality(grille) = 9 and matiere = 'logique'))
);

create index if not exists contenu_questions_classe_matiere_idx on contenu_questions (classe, matiere, statut);
create index if not exists contenu_questions_passage_idx on contenu_questions (passage_id);

-- ---------------------------------------------------------------------------
-- 4. Paquets publiés (ce que le jeu télécharge) : une ligne par classe + matière.
-- ---------------------------------------------------------------------------
create table if not exists contenu_paquets (
	classe text not null,
	matiere text not null,
	version integer not null default 1,
	empreinte text not null,          -- md5 du contenu : la version ne monte que si le contenu change
	nb_questions integer not null,
	donnees jsonb not null,
	publie_le timestamptz not null default now(),
	primary key (classe, matiere)
);

-- ---------------------------------------------------------------------------
-- 5. Historique automatique des modifications / suppressions
-- ---------------------------------------------------------------------------
create table if not exists contenu_historique (
	id bigint primary key generated always as identity,
	table_nom text not null,
	ligne_id integer not null,
	operation text not null,          -- UPDATE ou DELETE
	ancienne_version jsonb not null,
	le timestamptz not null default now()
);
create index if not exists contenu_historique_ligne_idx on contenu_historique (table_nom, ligne_id);

create or replace function fn_contenu_trace()
returns trigger
language plpgsql
as $$
begin
	insert into contenu_historique (table_nom, ligne_id, operation, ancienne_version)
	values (tg_table_name, old.id, tg_op, to_jsonb(old));
	if tg_op = 'UPDATE' then
		new.modifie_le := now();
		return new;
	end if;
	return old;
end;
$$;

drop trigger if exists trace_questions on contenu_questions;
create trigger trace_questions before update or delete on contenu_questions
	for each row execute function fn_contenu_trace();
drop trigger if exists trace_passages on contenu_passages;
create trigger trace_passages before update or delete on contenu_passages
	for each row execute function fn_contenu_trace();
drop trigger if exists trace_cours on contenu_cours;
create trigger trace_cours before update or delete on contenu_cours
	for each row execute function fn_contenu_trace();

-- ---------------------------------------------------------------------------
-- 6. Sécurité : RLS activé SANS policy (même règle que les tables de comptes) -> personne
--    ne lit/écrit ces tables via l'API publique ; tout passe par les fonctions ci-dessous.
-- ---------------------------------------------------------------------------
alter table contenu_cours enable row level security;
alter table contenu_passages enable row level security;
alter table contenu_questions enable row level security;
alter table contenu_paquets enable row level security;
alter table contenu_historique enable row level security;

-- ---------------------------------------------------------------------------
-- 7. fn_publier : vérifie TOUT, puis remplace les paquets. En cas de problème, une erreur
--    est levée et RIEN n'est modifié (tout ou rien).
--    p_forcer = true autorise une baisse de plus de 50 % des questions d'un paquet
--    (sinon refusée : protège contre une suppression / dépublication massive accidentelle).
-- ---------------------------------------------------------------------------
create or replace function fn_publier(p_forcer boolean default false)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
	v_paire record;
	v_donnees jsonb;
	v_empreinte text;
	v_nb integer;
	v_ancien contenu_paquets%rowtype;
	v_rapport jsonb := '[]'::jsonb;
	v_probleme text;
begin
	-- a) Cohérence de la lecture
	select 'question ' || q.id || ' publiée mais son texte ' || q.passage_id || ' ne l''est pas' into v_probleme
	from contenu_questions q join contenu_passages p on p.id = q.passage_id
	where q.statut = 'publie' and p.statut <> 'publie' limit 1;
	if v_probleme is not null then raise exception 'publication_refusee: %', v_probleme; end if;

	select 'texte ' || p.id || ' publié sans aucune question publiée' into v_probleme
	from contenu_passages p
	where p.statut = 'publie'
	  and not exists (select 1 from contenu_questions q where q.passage_id = p.id and q.statut = 'publie')
	limit 1;
	if v_probleme is not null then raise exception 'publication_refusee: %', v_probleme; end if;

	select 'question ' || q.id || ' (' || q.classe || ') liée au texte ' || p.id || ' d''une autre classe (' || p.classe || ')' into v_probleme
	from contenu_questions q join contenu_passages p on p.id = q.passage_id
	where q.statut = 'publie' and q.classe <> p.classe limit 1;
	if v_probleme is not null then raise exception 'publication_refusee: %', v_probleme; end if;

	-- b) Cours liés : doivent être publiés
	select 'question ' || q.id || ' liée au cours ' || q.cours_id || ' non publié' into v_probleme
	from contenu_questions q join contenu_cours c on c.id = q.cours_id
	where q.statut = 'publie' and c.statut <> 'publie' limit 1;
	if v_probleme is not null then raise exception 'publication_refusee: %', v_probleme; end if;

	-- c) Un paquet existant ne doit pas disparaître en silence
	select 'le paquet ' || pk.classe || '/' || pk.matiere || ' n''aurait plus aucune question' into v_probleme
	from contenu_paquets pk
	where not exists (select 1 from contenu_questions q where q.classe = pk.classe and q.matiere = pk.matiere and q.statut = 'publie')
	limit 1;
	if v_probleme is not null and not p_forcer then raise exception 'publication_refusee: %', v_probleme; end if;

	-- d) Construction des paquets, un par classe + matière
	for v_paire in
		select distinct classe, matiere from contenu_questions where statut = 'publie' order by 1, 2
	loop
		select jsonb_build_object(
			'questions', coalesce((
				select jsonb_agg(jsonb_strip_nulls(jsonb_build_object(
					'id', q.id, 'enonce', q.enonce, 'reponse', q.bonne_reponse,
					'choix', to_jsonb(q.mauvais_choix), 'grille', to_jsonb(q.grille),
					'passage', q.passage_id, 'type', q.type_lecture, 'cours', q.cours_id
				)) order by q.id)
				from contenu_questions q
				where q.classe = v_paire.classe and q.matiere = v_paire.matiere and q.statut = 'publie'
			), '[]'::jsonb),
			'passages', coalesce((
				select jsonb_agg(jsonb_build_object('id', p.id, 'texte', p.texte) order by p.id)
				from contenu_passages p
				where p.statut = 'publie' and p.id in (
					select q.passage_id from contenu_questions q
					where q.classe = v_paire.classe and q.matiere = v_paire.matiere and q.statut = 'publie')
			), '[]'::jsonb),
			'cours', coalesce((
				select jsonb_agg(jsonb_build_object('id', c.id, 'titre', c.titre, 'contenu', c.contenu) order by c.id)
				from contenu_cours c
				where c.statut = 'publie' and c.id in (
					select q.cours_id from contenu_questions q
					where q.classe = v_paire.classe and q.matiere = v_paire.matiere and q.statut = 'publie')
			), '[]'::jsonb)
		) into v_donnees;

		v_nb := jsonb_array_length(v_donnees -> 'questions');
		v_empreinte := md5(v_donnees::text);

		select * into v_ancien from contenu_paquets where classe = v_paire.classe and matiere = v_paire.matiere;
		if found then
			if v_ancien.empreinte = v_empreinte then
				continue; -- rien n'a changé : on garde la même version
			end if;
			if v_nb < v_ancien.nb_questions / 2 and not p_forcer then
				raise exception 'publication_refusee: %/% passerait de % à % questions (relancer avec fn_publier(true) si c''est voulu)',
					v_paire.classe, v_paire.matiere, v_ancien.nb_questions, v_nb;
			end if;
			update contenu_paquets
			set version = version + 1, empreinte = v_empreinte, nb_questions = v_nb, donnees = v_donnees, publie_le = now()
			where classe = v_paire.classe and matiere = v_paire.matiere;
		else
			insert into contenu_paquets (classe, matiere, empreinte, nb_questions, donnees)
			values (v_paire.classe, v_paire.matiere, v_empreinte, v_nb, v_donnees);
		end if;

		v_rapport := v_rapport || jsonb_build_object('paquet', v_paire.classe || '/' || v_paire.matiere, 'questions', v_nb);
	end loop;

	-- e) Paquets devenus vides (seulement possible avec p_forcer) : retirés
	delete from contenu_paquets pk
	where not exists (select 1 from contenu_questions q where q.classe = pk.classe and q.matiere = pk.matiere and q.statut = 'publie');

	return jsonb_build_object('paquets_mis_a_jour', v_rapport);
end;
$$;

-- ---------------------------------------------------------------------------
-- 8. Lecture par le jeu
-- ---------------------------------------------------------------------------
-- Versions de tous les paquets, ex. {"cp/math": 3, "ce1/lecture": 1, ...}
create or replace function fn_manifeste()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
	select coalesce(jsonb_object_agg(classe || '/' || matiere, version), '{}'::jsonb) from contenu_paquets;
$$;

-- Contenu d'un paquet (+ sa version, pour que le jeu la mémorise avec le cache)
create or replace function fn_paquet(p_classe text, p_matiere text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
	select donnees || jsonb_build_object('version', version)
	from contenu_paquets where classe = p_classe and matiere = p_matiere;
$$;

-- ---------------------------------------------------------------------------
-- 9. Droits : le jeu (rôle anon) peut SEULEMENT lire manifeste + paquets.
--    Par défaut Postgres autorise tout le monde à exécuter une fonction : on retire ce droit
--    pour fn_publier (réservée à l'administration, via Studio ou le tunnel).
-- ---------------------------------------------------------------------------
revoke execute on function fn_publier(boolean) from public, anon, authenticated;
revoke execute on function fn_contenu_trace() from public, anon, authenticated;
grant execute on function fn_manifeste() to anon, authenticated;
grant execute on function fn_paquet(text, text) to anon, authenticated;
