-- AUDITS_LOG #36 (2026-10-03) : anglais CP, noms comptables ramenes au singulier (pas de pluriel au programme du CP).
begin;
update contenu_questions set enonce = 'Comment dit-on "j''ai une pomme" en anglais ?', bonne_reponse = 'I have an apple', mauvais_choix = array['I have an egg','I have a pencil','I have a cat'], modifie_le = now() where id = 18335;
update contenu_questions set enonce = 'Que veut dire "an apple" en français ?', bonne_reponse = 'une pomme', mauvais_choix = array['un crayon','une règle','un chien'], modifie_le = now() where id = 18336;
update contenu_questions set enonce = 'Comment dit-on "j''ai une banane" en anglais ?', bonne_reponse = 'I have a banana', mauvais_choix = array['I see a frog','I see a bird','I have a pen'], modifie_le = now() where id = 18337;
update contenu_questions set enonce = 'Que veut dire "a banana" en français ?', bonne_reponse = 'une banane', mauvais_choix = array['une gomme','un chat','un crayon'], modifie_le = now() where id = 18338;
update contenu_questions set enonce = 'Comment dit-on "j''ai un oeuf" en anglais ?', bonne_reponse = 'I have an egg', mauvais_choix = array['I have a rubber','I see a duck','I see a frog'], modifie_le = now() where id = 18339;
update contenu_questions set enonce = 'Que veut dire "an egg" en français ?', bonne_reponse = 'un oeuf', mauvais_choix = array['un lapin','une gomme','une banane'], modifie_le = now() where id = 18340;
update contenu_questions set enonce = 'Comment dit-on "j''ai un gâteau" en anglais ?', bonne_reponse = 'I have a cake', mauvais_choix = array['I see a frog','I have a banana','I have an apple'], modifie_le = now() where id = 18341;
update contenu_questions set enonce = 'Que veut dire "a cake" en français ?', bonne_reponse = 'un gâteau', mauvais_choix = array['une banane','une pomme','un stylo'], modifie_le = now() where id = 18342;
update contenu_questions set enonce = 'Comment dit-on "j''ai un crayon" en anglais ?', bonne_reponse = 'I have a pencil', mauvais_choix = array['I have a dog','I have a cat','I have an apple'], modifie_le = now() where id = 18343;
update contenu_questions set enonce = 'Que veut dire "a pencil" en français ?', bonne_reponse = 'un crayon', mauvais_choix = array['un stylo','un chien','une règle'], modifie_le = now() where id = 18344;
update contenu_questions set enonce = 'Comment dit-on "une gomme" en anglais ?', bonne_reponse = 'a rubber', mauvais_choix = array['a cat','a rabbit','a banana'], modifie_le = now() where id = 18345;
update contenu_questions set enonce = 'Que veut dire "a rubber" en français ?', bonne_reponse = 'une gomme', mauvais_choix = array['un livre','un stylo','une banane'], modifie_le = now() where id = 18346;
update contenu_questions set enonce = 'Comment dit-on "une règle" en anglais ?', bonne_reponse = 'a ruler', mauvais_choix = array['a dog','a pen','an egg'], modifie_le = now() where id = 18347;
update contenu_questions set enonce = 'Que veut dire "a ruler" en français ?', bonne_reponse = 'une règle', mauvais_choix = array['un lapin','un chien','un oeuf'], modifie_le = now() where id = 18348;
update contenu_questions set enonce = 'Comment dit-on "un livre" en anglais ?', bonne_reponse = 'a book', mauvais_choix = array['a cat','a ruler','a rabbit'], modifie_le = now() where id = 18349;
update contenu_questions set enonce = 'Que veut dire "a book" en français ?', bonne_reponse = 'un livre', mauvais_choix = array['un lapin','une banane','un crayon'], modifie_le = now() where id = 18350;
update contenu_questions set enonce = 'Comment dit-on "un stylo" en anglais ?', bonne_reponse = 'a pen', mauvais_choix = array['a rabbit','an apple','a book'], modifie_le = now() where id = 18351;
update contenu_questions set enonce = 'Que veut dire "a pen" en français ?', bonne_reponse = 'un stylo', mauvais_choix = array['une règle','un lapin','une banane'], modifie_le = now() where id = 18352;
update contenu_questions set enonce = 'Comment dit-on "un chat" en anglais ?', bonne_reponse = 'a cat', mauvais_choix = array['a book','a pen','a pencil'], modifie_le = now() where id = 18353;
update contenu_questions set enonce = 'Que veut dire "a cat" en français ?', bonne_reponse = 'un chat', mauvais_choix = array['un chien','un crayon','une pomme'], modifie_le = now() where id = 18354;
update contenu_questions set enonce = 'Comment dit-on "un chien" en anglais ?', bonne_reponse = 'a dog', mauvais_choix = array['a cat','a pen','a banana'], modifie_le = now() where id = 18355;
update contenu_questions set enonce = 'Que veut dire "a dog" en français ?', bonne_reponse = 'un chien', mauvais_choix = array['une règle','une banane','un lapin'], modifie_le = now() where id = 18356;
update contenu_questions set enonce = 'Comment dit-on "un lapin" en anglais ?', bonne_reponse = 'a rabbit', mauvais_choix = array['a cat','a rubber','a dog'], modifie_le = now() where id = 18359;
update contenu_questions set enonce = 'Que veut dire "a rabbit" en français ?', bonne_reponse = 'un lapin', mauvais_choix = array['un stylo','un chat','un crayon'], modifie_le = now() where id = 18360;
update contenu_questions set enonce = 'Comment dit-on "une pomme" en anglais ?', bonne_reponse = 'an apple', mauvais_choix = array['a rabbit','a dog','a pen'], modifie_le = now() where id = 18369;
update contenu_questions set enonce = 'Comment dit-on "une banane" en anglais ?', bonne_reponse = 'a banana', mauvais_choix = array['a cat','a rabbit','a pencil'], modifie_le = now() where id = 18371;
update contenu_questions set enonce = 'Comment dit-on "un oeuf" en anglais ?', bonne_reponse = 'an egg', mauvais_choix = array['a cat','a dog','a rubber'], modifie_le = now() where id = 18373;
update contenu_questions set enonce = 'Comment dit-on "un gâteau" en anglais ?', bonne_reponse = 'a cake', mauvais_choix = array['an egg','a pen','a banana'], modifie_le = now() where id = 18375;
update contenu_questions set enonce = 'Comment dit-on "un crayon" en anglais ?', bonne_reponse = 'a pencil', mauvais_choix = array['an apple','a book','an egg'], modifie_le = now() where id = 18377;
update contenu_questions set enonce = 'Comment dit-on "je vois un oiseau" en anglais ?', bonne_reponse = 'I see a bird', mauvais_choix = array['I see a frog','I see a pig','I have an egg'], modifie_le = now() where id = 18357;
update contenu_questions set enonce = 'Que veut dire "a bird" en français ?', bonne_reponse = 'un oiseau', mauvais_choix = array['un canard','un cochon','une vache'], modifie_le = now() where id = 18358;
update contenu_questions set enonce = 'Comment dit-on "je vois une vache" en anglais ?', bonne_reponse = 'I see a cow', mauvais_choix = array['I have a ruler','I see a bird','I have a cake'], modifie_le = now() where id = 18361;
update contenu_questions set enonce = 'Que veut dire "a cow" en français ?', bonne_reponse = 'une vache', mauvais_choix = array['une grenouille','un cochon','un canard'], modifie_le = now() where id = 18362;
update contenu_questions set enonce = 'Comment dit-on "je vois un cochon" en anglais ?', bonne_reponse = 'I see a pig', mauvais_choix = array['I see a cow','I have an apple','I have a rubber'], modifie_le = now() where id = 18363;
update contenu_questions set enonce = 'Que veut dire "a pig" en français ?', bonne_reponse = 'un cochon', mauvais_choix = array['un canard','une grenouille','une vache'], modifie_le = now() where id = 18364;
update contenu_questions set enonce = 'Comment dit-on "je vois un canard" en anglais ?', bonne_reponse = 'I see a duck', mauvais_choix = array['I have a rabbit','I have a ruler','I have a dog'], modifie_le = now() where id = 18365;
update contenu_questions set enonce = 'Que veut dire "a duck" en français ?', bonne_reponse = 'un canard', mauvais_choix = array['un cochon','une grenouille','une vache'], modifie_le = now() where id = 18366;
update contenu_questions set enonce = 'Comment dit-on "je vois une grenouille" en anglais ?', bonne_reponse = 'I see a frog', mauvais_choix = array['I have a pencil','I have a pen','I have a cat'], modifie_le = now() where id = 18367;
update contenu_questions set enonce = 'Que veut dire "a frog" en français ?', bonne_reponse = 'une grenouille', mauvais_choix = array['une vache','un cochon','un canard'], modifie_le = now() where id = 18368;
update contenu_questions set enonce = 'Comment dit-on "un oiseau" en anglais ?', bonne_reponse = 'a bird', mauvais_choix = array['a pig','a frog','a cow'], modifie_le = now() where id = 18391;
update contenu_questions set enonce = 'Comment dit-on "une vache" en anglais ?', bonne_reponse = 'a cow', mauvais_choix = array['a pig','a duck','a bird'], modifie_le = now() where id = 18395;
update contenu_questions set enonce = 'Comment dit-on "un cochon" en anglais ?', bonne_reponse = 'a pig', mauvais_choix = array['a frog','a cow','a duck'], modifie_le = now() where id = 18397;
update contenu_questions set enonce = 'Comment dit-on "un canard" en anglais ?', bonne_reponse = 'a duck', mauvais_choix = array['a bird','a cow','a frog'], modifie_le = now() where id = 18399;
update contenu_questions set enonce = 'Comment dit-on "une grenouille" en anglais ?', bonne_reponse = 'a frog', mauvais_choix = array['a duck','a bird','a cow'], modifie_le = now() where id = 18401;
update contenu_questions set enonce = 'Comment dit-on "j''aime le rouge" en anglais ?', bonne_reponse = 'I like red', mauvais_choix = array['I like cheese','I like green','I like yellow'], modifie_le = now() where id = 18190;
update contenu_questions set enonce = 'Comment dit-on "je n''aime pas le rouge" en anglais ?', bonne_reponse = 'I don''t like red', mauvais_choix = array['I don''t like chocolate','I don''t like blue','I don''t like cheese'], modifie_le = now() where id = 18191;
update contenu_questions set enonce = 'Comment dit-on "j''aime le bleu" en anglais ?', bonne_reponse = 'I like blue', mauvais_choix = array['I like cheese','I like black','I like white'], modifie_le = now() where id = 18192;
update contenu_questions set enonce = 'Comment dit-on "je n''aime pas le bleu" en anglais ?', bonne_reponse = 'I don''t like blue', mauvais_choix = array['I don''t like orange','I don''t like red','I don''t like purple'], modifie_le = now() where id = 18193;
update contenu_questions set enonce = 'Comment dit-on "j''aime le vert" en anglais ?', bonne_reponse = 'I like green', mauvais_choix = array['I like blue','I like yellow','I like white'], modifie_le = now() where id = 18194;
update contenu_questions set enonce = 'Comment dit-on "je n''aime pas le vert" en anglais ?', bonne_reponse = 'I don''t like green', mauvais_choix = array['I don''t like blue','I don''t like chocolate','I don''t like orange'], modifie_le = now() where id = 18195;
update contenu_questions set enonce = 'Comment dit-on "j''aime le jaune" en anglais ?', bonne_reponse = 'I like yellow', mauvais_choix = array['I like cheese','I like white','I like black'], modifie_le = now() where id = 18196;
update contenu_questions set enonce = 'Comment dit-on "je n''aime pas le jaune" en anglais ?', bonne_reponse = 'I don''t like yellow', mauvais_choix = array['I don''t like milk','I don''t like chocolate','I don''t like green'], modifie_le = now() where id = 18197;
update contenu_questions set enonce = 'Comment dit-on "j''aime le noir" en anglais ?', bonne_reponse = 'I like black', mauvais_choix = array['I like red','I like cheese','I like blue'], modifie_le = now() where id = 18198;
update contenu_questions set enonce = 'Comment dit-on "je n''aime pas le noir" en anglais ?', bonne_reponse = 'I don''t like black', mauvais_choix = array['I don''t like chocolate','I don''t like cheese','I don''t like blue'], modifie_le = now() where id = 18199;
update contenu_questions set enonce = 'Comment dit-on "le violet" en anglais ?', bonne_reponse = 'purple', mauvais_choix = array['white','yellow','cheese'], modifie_le = now() where id = 18206;
update contenu_questions set enonce = 'Comment dit-on "le pain" en anglais ?', bonne_reponse = 'bread', mauvais_choix = array['purple','blue','orange'], modifie_le = now() where id = 18213;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18224;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18225;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18226;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18227;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18228;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18229;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18230;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18231;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18232;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18233;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18234;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18235;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18236;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18237;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18238;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18239;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18240;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18241;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18242;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18243;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18244;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18245;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18246;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18247;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18248;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18249;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18250;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18251;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18252;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18253;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18254;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18255;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20021;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19297;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19298;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 22327;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 22328;
commit;
select fn_publier();
