-- AUDITS_LOG #35 (2026-10-03) : anglais, phrases-cadres ramenees au mot essentiel ("j'ai un animal, c'est un chien" -> "un chien").
begin;
update contenu_questions set enonce = 'Comment dit-on "un ours" en anglais ?', bonne_reponse = 'a bear', mauvais_choix = array['a snake','an elephant','a lion'], modifie_le = now() where id = 19464;
update contenu_questions set enonce = 'Que veut dire "pencils" en français ?', bonne_reponse = 'des crayons', mauvais_choix = array['des chats','des règles','des livres'], modifie_le = now() where id = 19490;
update contenu_questions set enonce = 'Que veut dire "rubbers" en français ?', bonne_reponse = 'des gommes', mauvais_choix = array['des livres','des crayons','des chats'], modifie_le = now() where id = 19492;
update contenu_questions set enonce = 'Que veut dire "rulers" en français ?', bonne_reponse = 'des règles', mauvais_choix = array['des chiens','des crayons','des gommes'], modifie_le = now() where id = 19494;
update contenu_questions set enonce = 'Que veut dire "books" en français ?', bonne_reponse = 'des livres', mauvais_choix = array['des lapins','des crayons','des chats'], modifie_le = now() where id = 19496;
update contenu_questions set enonce = 'Que veut dire "cats" en français ?', bonne_reponse = 'des chats', mauvais_choix = array['des crayons','des lapins','des livres'], modifie_le = now() where id = 19498;
update contenu_questions set enonce = 'Comment dit-on "des chiens" en anglais ?', bonne_reponse = 'dogs', mauvais_choix = array['rubbers','cats','books'], modifie_le = now() where id = 19499;
update contenu_questions set enonce = 'Que veut dire "dogs" en français ?', bonne_reponse = 'des chiens', mauvais_choix = array['des livres','des gommes','des chats'], modifie_le = now() where id = 19500;
update contenu_questions set enonce = 'Comment dit-on "des lapins" en anglais ?', bonne_reponse = 'rabbits', mauvais_choix = array['dogs','cats','books'], modifie_le = now() where id = 19503;
update contenu_questions set enonce = 'Que veut dire "rabbits" en français ?', bonne_reponse = 'des lapins', mauvais_choix = array['des gommes','des livres','des chiens'], modifie_le = now() where id = 19504;
update contenu_questions set enonce = 'Comment dit-on "des crayons" en anglais ?', bonne_reponse = 'pencils', mauvais_choix = array['rulers','dogs','rubbers'], modifie_le = now() where id = 19505;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19506;
update contenu_questions set enonce = 'Comment dit-on "des gommes" en anglais ?', bonne_reponse = 'rubbers', mauvais_choix = array['books','cats','dogs'], modifie_le = now() where id = 19507;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19508;
update contenu_questions set enonce = 'Comment dit-on "des règles" en anglais ?', bonne_reponse = 'rulers', mauvais_choix = array['books','dogs','cats'], modifie_le = now() where id = 19509;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19510;
update contenu_questions set enonce = 'Comment dit-on "des livres" en anglais ?', bonne_reponse = 'books', mauvais_choix = array['rulers','dogs','pencils'], modifie_le = now() where id = 19511;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19512;
update contenu_questions set enonce = 'Comment dit-on "des chats" en anglais ?', bonne_reponse = 'cats', mauvais_choix = array['rulers','dogs','rubbers'], modifie_le = now() where id = 19513;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19514;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19515;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19516;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19519;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19520;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19521;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19522;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19523;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19524;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19525;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19526;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19527;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19528;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19529;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19530;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19531;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19532;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19535;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19536;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19537;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19538;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19539;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19540;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19541;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19542;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19543;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19544;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19545;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19546;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19547;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19548;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19551;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19552;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19553;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19554;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19555;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19556;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19557;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19558;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19559;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19560;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19561;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19562;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19563;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19564;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19567;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19568;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19502;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19517;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19518;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19533;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19534;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19549;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19550;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19565;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 19566;
update contenu_questions set enonce = 'Comment dit-on "la lecture" en anglais ?', bonne_reponse = 'reading', mauvais_choix = array['singing','cycling','drawing'], modifie_le = now() where id = 19357;
update contenu_questions set enonce = 'Comment dit-on "le chant" en anglais ?', bonne_reponse = 'singing', mauvais_choix = array['swimming','reading','dancing'], modifie_le = now() where id = 19358;
update contenu_questions set enonce = 'Comment dit-on "la course" en anglais ?', bonne_reponse = 'running', mauvais_choix = array['reading','cycling','football'], modifie_le = now() where id = 19359;
update contenu_questions set enonce = 'Comment dit-on "les serpents" en anglais ?', bonne_reponse = 'snakes', mauvais_choix = array['monkeys','lions','tigers'], modifie_le = now() where id = 19372;
update contenu_questions set enonce = 'Comment dit-on "les lions" en anglais ?', bonne_reponse = 'lions', mauvais_choix = array['elephants','snakes','monkeys'], modifie_le = now() where id = 19373;
update contenu_questions set enonce = 'Comment dit-on "les éléphants" en anglais ?', bonne_reponse = 'elephants', mauvais_choix = array['monkeys','lions','bears'], modifie_le = now() where id = 19374;
update contenu_questions set enonce = 'Comment dit-on "les singes" en anglais ?', bonne_reponse = 'monkeys', mauvais_choix = array['tigers','elephants','snakes'], modifie_le = now() where id = 19375;
update contenu_questions set enonce = 'Comment dit-on "les tigres" en anglais ?', bonne_reponse = 'tigers', mauvais_choix = array['lions','bears','monkeys'], modifie_le = now() where id = 19376;
update contenu_questions set enonce = 'Comment dit-on "les ours" en anglais ?', bonne_reponse = 'bears', mauvais_choix = array['elephants','tigers','snakes'], modifie_le = now() where id = 19377;
update contenu_questions set enonce = 'Comment dit-on "la lecture" en anglais ?', bonne_reponse = 'reading', mauvais_choix = array['football','cycling','swimming'], modifie_le = now() where id = 19394;
update contenu_questions set enonce = 'Comment dit-on "le chant" en anglais ?', bonne_reponse = 'singing', mauvais_choix = array['drawing','cycling','football'], modifie_le = now() where id = 19395;
update contenu_questions set enonce = 'Comment dit-on "la course" en anglais ?', bonne_reponse = 'running', mauvais_choix = array['football','dancing','drawing'], modifie_le = now() where id = 19396;
update contenu_questions set enonce = 'Comment dit-on "les serpents" en anglais ?', bonne_reponse = 'snakes', mauvais_choix = array['tigers','bears','lions'], modifie_le = now() where id = 19409;
update contenu_questions set enonce = 'Comment dit-on "les lions" en anglais ?', bonne_reponse = 'lions', mauvais_choix = array['tigers','bears','monkeys'], modifie_le = now() where id = 19410;
update contenu_questions set enonce = 'Comment dit-on "les éléphants" en anglais ?', bonne_reponse = 'elephants', mauvais_choix = array['snakes','lions','bears'], modifie_le = now() where id = 19411;
update contenu_questions set enonce = 'Comment dit-on "les singes" en anglais ?', bonne_reponse = 'monkeys', mauvais_choix = array['tigers','bears','elephants'], modifie_le = now() where id = 19412;
update contenu_questions set enonce = 'Comment dit-on "les tigres" en anglais ?', bonne_reponse = 'tigers', mauvais_choix = array['bears','lions','elephants'], modifie_le = now() where id = 19413;
update contenu_questions set enonce = 'Comment dit-on "les ours" en anglais ?', bonne_reponse = 'bears', mauvais_choix = array['elephants','snakes','monkeys'], modifie_le = now() where id = 19414;
update contenu_questions set enonce = 'Comment dit-on "des cochons" en anglais ?', bonne_reponse = 'pigs', mauvais_choix = array['snakes','tigers','rabbits'], modifie_le = now() where id = 20011;
update contenu_questions set enonce = 'Comment dit-on "des chiens" en anglais ?', bonne_reponse = 'dogs', mauvais_choix = array['pigs','monkeys','rabbits'], modifie_le = now() where id = 20012;
update contenu_questions set enonce = 'Comment dit-on "des ours" en anglais ?', bonne_reponse = 'bears', mauvais_choix = array['dogs','frogs','pigs'], modifie_le = now() where id = 20013;
update contenu_questions set enonce = 'Comment dit-on "des éléphants" en anglais ?', bonne_reponse = 'elephants', mauvais_choix = array['monkeys','ducks','pigs'], modifie_le = now() where id = 20014;
update contenu_questions set enonce = 'Comment dit-on "des oiseaux" en anglais ?', bonne_reponse = 'birds', mauvais_choix = array['lions','ducks','elephants'], modifie_le = now() where id = 20017;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20019;
update contenu_questions set enonce = 'Comment dit-on "des souriss" en anglais ?', bonne_reponse = 'mice', mauvais_choix = array['dogs','a pig','snakes'], modifie_le = now() where id = 20021;
update contenu_questions set enonce = 'Comment dit-on "des lapins" en anglais ?', bonne_reponse = 'rabbits', mauvais_choix = array['snakes','frogs','horses'], modifie_le = now() where id = 20024;
update contenu_questions set enonce = 'Comment dit-on "des canards" en anglais ?', bonne_reponse = 'ducks', mauvais_choix = array['horses','tigers','cats'], modifie_le = now() where id = 20026;
update contenu_questions set enonce = 'Comment dit-on "des grenouilles" en anglais ?', bonne_reponse = 'frogs', mauvais_choix = array['lions','rabbits','birds'], modifie_le = now() where id = 20028;
update contenu_questions set enonce = 'Comment dit-on "des chevaux" en anglais ?', bonne_reponse = 'horses', mauvais_choix = array['lions','elephants','dogs'], modifie_le = now() where id = 20029;
update contenu_questions set enonce = 'Comment dit-on "des tigres" en anglais ?', bonne_reponse = 'tigers', mauvais_choix = array['snakes','frogs','ducks'], modifie_le = now() where id = 20033;
update contenu_questions set enonce = 'Comment dit-on "des moutons" en anglais ?', bonne_reponse = 'sheep', mauvais_choix = array['monkeys','a cat','cats'], modifie_le = now() where id = 20034;
update contenu_questions set enonce = 'Comment dit-on "des poissons" en anglais ?', bonne_reponse = 'fish', mauvais_choix = array['a snake','cats','bears'], modifie_le = now() where id = 20035;
update contenu_questions set enonce = 'Comment dit-on "des serpents" en anglais ?', bonne_reponse = 'snakes', mauvais_choix = array['rabbits','cows','bears'], modifie_le = now() where id = 20036;
update contenu_questions set enonce = 'Comment dit-on "des chats" en anglais ?', bonne_reponse = 'cats', mauvais_choix = array['lions','snakes','frogs'], modifie_le = now() where id = 20038;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20039;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20040;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20041;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20047;
update contenu_questions set enonce = 'Comment dit-on "des lions" en anglais ?', bonne_reponse = 'lions', mauvais_choix = array['ducks','elephants','bears'], modifie_le = now() where id = 20050;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20051;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20052;
update contenu_questions set enonce = 'Comment dit-on "des singes" en anglais ?', bonne_reponse = 'monkeys', mauvais_choix = array['cows','cats','bears'], modifie_le = now() where id = 20053;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20054;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20055;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20056;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20059;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20061;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20062;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20063;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20064;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20067;
update contenu_questions set enonce = 'Comment dit-on "des vaches" en anglais ?', bonne_reponse = 'cows', mauvais_choix = array['monkeys','rabbits','horses'], modifie_le = now() where id = 20069;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20072;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20075;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20076;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20077;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20078;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20093;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20096;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20099;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20101;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20104;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20109;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20118;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20125;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20137;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20138;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20139;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20140;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20141;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20142;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20143;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20144;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20145;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20146;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20147;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20148;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20149;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20150;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20151;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20152;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20153;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20155;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20156;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20157;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20158;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20159;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20160;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20161;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20164;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20165;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20167;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20168;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20169;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20170;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20171;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20172;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20173;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20174;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20175;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20176;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20177;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20178;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20179;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20180;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20181;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20182;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20183;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20184;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20185;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20186;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20187;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20188;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20189;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20190;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20191;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20192;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20193;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20194;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20195;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20196;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20197;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20198;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20199;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20200;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20201;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20202;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20205;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20206;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20207;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20208;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20209;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20210;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20211;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20212;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20213;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20214;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20215;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20216;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20217;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20218;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20219;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20220;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20259;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20260;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20261;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20262;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20263;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20264;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20265;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20266;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20271;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20272;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20273;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20274;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20275;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20276;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20277;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20278;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20279;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20280;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20281;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20282;
update contenu_questions set enonce = 'Comment dit-on "un chien" en anglais ?', bonne_reponse = 'a dog', mauvais_choix = array['a lion','a cow','a rabbit'], modifie_le = now() where id = 20283;
update contenu_questions set enonce = 'Comment dit-on "un chat" en anglais ?', bonne_reponse = 'a cat', mauvais_choix = array['a tiger','a lion','a frog'], modifie_le = now() where id = 20284;
update contenu_questions set enonce = 'Comment dit-on "une souris" en anglais ?', bonne_reponse = 'a mouse', mauvais_choix = array['an elephant','a frog','a horse'], modifie_le = now() where id = 20285;
update contenu_questions set enonce = 'Comment dit-on "un lapin" en anglais ?', bonne_reponse = 'a rabbit', mauvais_choix = array['a snake','a frog','a mouse'], modifie_le = now() where id = 20286;
update contenu_questions set enonce = 'Comment dit-on "un oiseau" en anglais ?', bonne_reponse = 'a bird', mauvais_choix = array['a sheep','a frog','an elephant'], modifie_le = now() where id = 20287;
update contenu_questions set enonce = 'Comment dit-on "une vache" en anglais ?', bonne_reponse = 'a cow', mauvais_choix = array['a tiger','a frog','a pig'], modifie_le = now() where id = 20288;
update contenu_questions set enonce = 'Comment dit-on "un cochon" en anglais ?', bonne_reponse = 'a pig', mauvais_choix = array['a rabbit','a lion','a monkey'], modifie_le = now() where id = 20289;
update contenu_questions set enonce = 'Comment dit-on "un cheval" en anglais ?', bonne_reponse = 'a horse', mauvais_choix = array['a rabbit','a cow','a monkey'], modifie_le = now() where id = 20290;
update contenu_questions set enonce = 'Comment dit-on "un mouton" en anglais ?', bonne_reponse = 'a sheep', mauvais_choix = array['a tiger','an elephant','a rabbit'], modifie_le = now() where id = 20291;
update contenu_questions set enonce = 'Comment dit-on "un poisson" en anglais ?', bonne_reponse = 'a fish', mauvais_choix = array['a monkey','a lion','a frog'], modifie_le = now() where id = 20292;
update contenu_questions set enonce = 'Comment dit-on "un canard" en anglais ?', bonne_reponse = 'a duck', mauvais_choix = array['a mouse','a tiger','an elephant'], modifie_le = now() where id = 20293;
update contenu_questions set enonce = 'Comment dit-on "une grenouille" en anglais ?', bonne_reponse = 'a frog', mauvais_choix = array['a horse','a cow','a duck'], modifie_le = now() where id = 20294;
update contenu_questions set enonce = 'Comment dit-on "un serpent" en anglais ?', bonne_reponse = 'a snake', mauvais_choix = array['a rabbit','a lion','an elephant'], modifie_le = now() where id = 20295;
update contenu_questions set enonce = 'Comment dit-on "un lion" en anglais ?', bonne_reponse = 'a lion', mauvais_choix = array['a pig','a sheep','a snake'], modifie_le = now() where id = 20296;
update contenu_questions set enonce = 'Comment dit-on "un éléphant" en anglais ?', bonne_reponse = 'an elephant', mauvais_choix = array['a sheep','a monkey','a horse'], modifie_le = now() where id = 20297;
update contenu_questions set enonce = 'Comment dit-on "un singe" en anglais ?', bonne_reponse = 'a monkey', mauvais_choix = array['a rabbit','a cow','a pig'], modifie_le = now() where id = 20298;
update contenu_questions set enonce = 'Comment dit-on "un tigre" en anglais ?', bonne_reponse = 'a tiger', mauvais_choix = array['a cow','a dog','a duck'], modifie_le = now() where id = 20299;
update contenu_questions set enonce = 'Comment dit-on "un ours" en anglais ?', bonne_reponse = 'a bear', mauvais_choix = array['a tiger','a frog','a monkey'], modifie_le = now() where id = 20300;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20301;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20302;
update contenu_questions set enonce = 'Comment dit-on "des souris" en anglais ?', bonne_reponse = 'mice', mauvais_choix = array['pigs','a cow','bears'], modifie_le = now() where id = 20303;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20304;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20305;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20306;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20307;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20308;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20309;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20310;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20311;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20312;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20313;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20314;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20315;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20316;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20317;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20318;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20319;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20320;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20321;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20322;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20323;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20324;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20325;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20326;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20327;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20328;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20329;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20330;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20331;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20332;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20333;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20334;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20335;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20336;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20383;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20384;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20385;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20386;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20387;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20388;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20389;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20390;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20391;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20392;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20393;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20394;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20395;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20396;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20397;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20398;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20399;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20400;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20401;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20402;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20403;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20404;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20405;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20406;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20407;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20408;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20409;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20410;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20411;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20412;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20413;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20414;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20415;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20416;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20417;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 20418;
update contenu_questions set enonce = 'Comment dit-on "sciences" en anglais ?', bonne_reponse = 'Science', mauvais_choix = array['Music','Art','PE'], modifie_le = now() where id = 20468;
update contenu_questions set enonce = 'Que veut dire "football" en français ?', bonne_reponse = 'le football', mauvais_choix = array['la lecture','la course','la danse'], modifie_le = now() where id = 20444;
update contenu_questions set enonce = 'Que veut dire "swimming" en français ?', bonne_reponse = 'la natation', mauvais_choix = array['la lecture','le football','la course'], modifie_le = now() where id = 20446;
update contenu_questions set enonce = 'Que veut dire "cycling" en français ?', bonne_reponse = 'faire du vélo', mauvais_choix = array['le basket','le dessin','le football'], modifie_le = now() where id = 20448;
update contenu_questions set enonce = 'Que veut dire "dancing" en français ?', bonne_reponse = 'la danse', mauvais_choix = array['la course','la natation','le chant'], modifie_le = now() where id = 20450;
update contenu_questions set enonce = 'Que veut dire "drawing" en français ?', bonne_reponse = 'le dessin', mauvais_choix = array['la lecture','la danse','la course'], modifie_le = now() where id = 20452;
update contenu_questions set enonce = 'Comment dit-on "la lecture" en anglais ?', bonne_reponse = 'reading', mauvais_choix = array['swimming','cycling','running'], modifie_le = now() where id = 20453;
update contenu_questions set enonce = 'Que veut dire "reading" en français ?', bonne_reponse = 'la lecture', mauvais_choix = array['le chant','le dessin','le football'], modifie_le = now() where id = 20454;
update contenu_questions set enonce = 'Comment dit-on "le chant" en anglais ?', bonne_reponse = 'singing', mauvais_choix = array['dancing','cycling','drawing'], modifie_le = now() where id = 20455;
update contenu_questions set enonce = 'Que veut dire "singing" en français ?', bonne_reponse = 'le chant', mauvais_choix = array['le basket','la natation','la lecture'], modifie_le = now() where id = 20456;
update contenu_questions set enonce = 'Comment dit-on "la course" en anglais ?', bonne_reponse = 'running', mauvais_choix = array['basketball','drawing','dancing'], modifie_le = now() where id = 20457;
update contenu_questions set enonce = 'Que veut dire "running" en français ?', bonne_reponse = 'la course', mauvais_choix = array['la danse','la natation','le basket'], modifie_le = now() where id = 20458;
update contenu_questions set enonce = 'Comment dit-on "le tennis" en anglais ?', bonne_reponse = 'tennis', mauvais_choix = array['swimming','dancing','drawing'], modifie_le = now() where id = 20459;
update contenu_questions set enonce = 'Que veut dire "tennis" en français ?', bonne_reponse = 'le tennis', mauvais_choix = array['la danse','le football','le chant'], modifie_le = now() where id = 20460;
update contenu_questions set enonce = 'Comment dit-on "le basket" en anglais ?', bonne_reponse = 'basketball', mauvais_choix = array['running','singing','dancing'], modifie_le = now() where id = 20461;
update contenu_questions set enonce = 'Que veut dire "basketball" en français ?', bonne_reponse = 'le basket', mauvais_choix = array['le football','le chant','la danse'], modifie_le = now() where id = 20462;
update contenu_questions set enonce = 'Que veut dire "apples" en français ?', bonne_reponse = 'les pommes', mauvais_choix = array['les oeufs','les bananes','le tennis'], modifie_le = now() where id = 20338;
update contenu_questions set enonce = 'Que veut dire "bananas" en français ?', bonne_reponse = 'les bananes', mauvais_choix = array['les oeufs','le tennis','les pommes'], modifie_le = now() where id = 20340;
update contenu_questions set enonce = 'Que veut dire "bread" en français ?', bonne_reponse = 'le pain', mauvais_choix = array['le lait','le dessin','la natation'], modifie_le = now() where id = 20342;
update contenu_questions set enonce = 'Que veut dire "milk" en français ?', bonne_reponse = 'le lait', mauvais_choix = array['la course','le chocolat','le football'], modifie_le = now() where id = 20344;
update contenu_questions set enonce = 'Que veut dire "cheese" en français ?', bonne_reponse = 'le fromage', mauvais_choix = array['le pain','la course','le basket'], modifie_le = now() where id = 20346;
update contenu_questions set enonce = 'Comment dit-on "les oeufs" en anglais ?', bonne_reponse = 'eggs', mauvais_choix = array['bananas','tennis','cakes'], modifie_le = now() where id = 20347;
update contenu_questions set enonce = 'Que veut dire "eggs" en français ?', bonne_reponse = 'les oeufs', mauvais_choix = array['les bananes','les pommes','le tennis'], modifie_le = now() where id = 20348;
update contenu_questions set enonce = 'Comment dit-on "le chocolat" en anglais ?', bonne_reponse = 'chocolate', mauvais_choix = array['reading','cycling','cheese'], modifie_le = now() where id = 20349;
update contenu_questions set enonce = 'Que veut dire "chocolate" en français ?', bonne_reponse = 'le chocolat', mauvais_choix = array['le chant','le pain','la viande'], modifie_le = now() where id = 20350;
update contenu_questions set enonce = 'Comment dit-on "les gâteaux" en anglais ?', bonne_reponse = 'cakes', mauvais_choix = array['apples','bananas','tennis'], modifie_le = now() where id = 20351;
update contenu_questions set enonce = 'Que veut dire "cakes" en français ?', bonne_reponse = 'les gâteaux', mauvais_choix = array['la course','le riz','le chocolat'], modifie_le = now() where id = 20352;
update contenu_questions set enonce = 'Comment dit-on "l''eau" en anglais ?', bonne_reponse = 'water', mauvais_choix = array['meat','fish','basketball'], modifie_le = now() where id = 20353;
update contenu_questions set enonce = 'Que veut dire "water" en français ?', bonne_reponse = 'l''eau', mauvais_choix = array['le pain','le basket','le dessin'], modifie_le = now() where id = 20354;
update contenu_questions set enonce = 'Comment dit-on "le riz" en anglais ?', bonne_reponse = 'rice', mauvais_choix = array['dancing','chocolate','cheese'], modifie_le = now() where id = 20355;
update contenu_questions set enonce = 'Que veut dire "rice" en français ?', bonne_reponse = 'le riz', mauvais_choix = array['la course','le basket','la viande'], modifie_le = now() where id = 20356;
update contenu_questions set enonce = 'Comment dit-on "la viande" en anglais ?', bonne_reponse = 'meat', mauvais_choix = array['bread','basketball','drawing'], modifie_le = now() where id = 20357;
update contenu_questions set enonce = 'Que veut dire "meat" en français ?', bonne_reponse = 'la viande', mauvais_choix = array['l''eau','le chocolat','la soupe'], modifie_le = now() where id = 20358;
update contenu_questions set enonce = 'Comment dit-on "la soupe" en anglais ?', bonne_reponse = 'soup', mauvais_choix = array['running','fish','singing'], modifie_le = now() where id = 20359;
update contenu_questions set enonce = 'Que veut dire "soup" en français ?', bonne_reponse = 'la soupe', mauvais_choix = array['le chant','la danse','le riz'], modifie_le = now() where id = 20360;
update contenu_questions set enonce = 'Comment dit-on "le poisson" en anglais ?', bonne_reponse = 'fish', mauvais_choix = array['soup','football','singing'], modifie_le = now() where id = 20361;
update contenu_questions set enonce = 'Que veut dire "fish" en français ?', bonne_reponse = 'le poisson', mauvais_choix = array['le riz','la course','les gâteaux'], modifie_le = now() where id = 20362;
update contenu_questions set enonce = 'Comment dit-on "le football" en anglais ?', bonne_reponse = 'football', mauvais_choix = array['water','chocolate','reading'], modifie_le = now() where id = 20363;
update contenu_questions set enonce = 'Que veut dire "football" en français ?', bonne_reponse = 'le football', mauvais_choix = array['la course','le fromage','le chocolat'], modifie_le = now() where id = 20364;
update contenu_questions set enonce = 'Comment dit-on "la natation" en anglais ?', bonne_reponse = 'swimming', mauvais_choix = array['milk','soup','meat'], modifie_le = now() where id = 20365;
update contenu_questions set enonce = 'Que veut dire "swimming" en français ?', bonne_reponse = 'la natation', mauvais_choix = array['la lecture','le chant','le basket'], modifie_le = now() where id = 20366;
update contenu_questions set enonce = 'Comment dit-on "faire du vélo" en anglais ?', bonne_reponse = 'cycling', mauvais_choix = array['football','rice','meat'], modifie_le = now() where id = 20367;
update contenu_questions set enonce = 'Que veut dire "cycling" en français ?', bonne_reponse = 'faire du vélo', mauvais_choix = array['les pommes','le fromage','l''eau'], modifie_le = now() where id = 20368;
update contenu_questions set enonce = 'Comment dit-on "la danse" en anglais ?', bonne_reponse = 'dancing', mauvais_choix = array['milk','chocolate','meat'], modifie_le = now() where id = 20369;
update contenu_questions set enonce = 'Que veut dire "dancing" en français ?', bonne_reponse = 'la danse', mauvais_choix = array['l''eau','le riz','le dessin'], modifie_le = now() where id = 20370;
update contenu_questions set enonce = 'Comment dit-on "le dessin" en anglais ?', bonne_reponse = 'drawing', mauvais_choix = array['cycling','milk','singing'], modifie_le = now() where id = 20371;
update contenu_questions set enonce = 'Que veut dire "drawing" en français ?', bonne_reponse = 'le dessin', mauvais_choix = array['la natation','la viande','le riz'], modifie_le = now() where id = 20372;
update contenu_questions set enonce = 'Comment dit-on "la lecture" en anglais ?', bonne_reponse = 'reading', mauvais_choix = array['swimming','dancing','basketball'], modifie_le = now() where id = 20373;
update contenu_questions set enonce = 'Que veut dire "reading" en français ?', bonne_reponse = 'la lecture', mauvais_choix = array['le chocolat','le lait','le pain'], modifie_le = now() where id = 20374;
update contenu_questions set enonce = 'Comment dit-on "le chant" en anglais ?', bonne_reponse = 'singing', mauvais_choix = array['water','cycling','swimming'], modifie_le = now() where id = 20375;
update contenu_questions set enonce = 'Que veut dire "singing" en français ?', bonne_reponse = 'le chant', mauvais_choix = array['le fromage','le football','le lait'], modifie_le = now() where id = 20376;
update contenu_questions set enonce = 'Comment dit-on "la course" en anglais ?', bonne_reponse = 'running', mauvais_choix = array['fish','milk','swimming'], modifie_le = now() where id = 20377;
update contenu_questions set enonce = 'Que veut dire "running" en français ?', bonne_reponse = 'la course', mauvais_choix = array['le chocolat','le riz','la natation'], modifie_le = now() where id = 20378;
update contenu_questions set enonce = 'Comment dit-on "le tennis" en anglais ?', bonne_reponse = 'tennis', mauvais_choix = array['eggs','bananas','apples'], modifie_le = now() where id = 20379;
update contenu_questions set enonce = 'Que veut dire "tennis" en français ?', bonne_reponse = 'le tennis', mauvais_choix = array['les pommes','les oeufs','les bananes'], modifie_le = now() where id = 20380;
update contenu_questions set enonce = 'Comment dit-on "le basket" en anglais ?', bonne_reponse = 'basketball', mauvais_choix = array['fish','soup','cheese'], modifie_le = now() where id = 20381;
update contenu_questions set enonce = 'Que veut dire "basketball" en français ?', bonne_reponse = 'le basket', mauvais_choix = array['le lait','le pain','les gâteaux'], modifie_le = now() where id = 20382;
update contenu_questions set enonce = 'Comment dit-on "un mari" en anglais ?', bonne_reponse = 'a husband', mauvais_choix = array['an uncle','a twin','a wife'], modifie_le = now() where id = 21258;
update contenu_questions set enonce = 'Comment dit-on "un jumeau" en anglais ?', bonne_reponse = 'a twin', mauvais_choix = array['a husband','a baby','a wife'], modifie_le = now() where id = 21451;
update contenu_questions set enonce = 'Comment dit-on "un neveu" en anglais ?', bonne_reponse = 'a nephew', mauvais_choix = array['a niece','a baby','a husband'], modifie_le = now() where id = 21460;
update contenu_questions set enonce = 'Comment dit-on "un oncle" en anglais ?', bonne_reponse = 'an uncle', mauvais_choix = array['a baby','an aunt','a niece'], modifie_le = now() where id = 21461;
update contenu_questions set enonce = 'Que veut dire "a wife" en français ?', bonne_reponse = 'une femme', mauvais_choix = array['un neveu','une nièce','un cousin'], modifie_le = now() where id = 110374;
update contenu_questions set enonce = 'Que veut dire "football" en français ?', bonne_reponse = 'le football', mauvais_choix = array['la natation','la course','le basket'], modifie_le = now() where id = 21411;
update contenu_questions set enonce = 'Que veut dire "swimming" en français ?', bonne_reponse = 'la natation', mauvais_choix = array['le basket','le chant','la lecture'], modifie_le = now() where id = 21413;
update contenu_questions set enonce = 'Que veut dire "cycling" en français ?', bonne_reponse = 'faire du vélo', mauvais_choix = array['le dessin','le tennis','le basket'], modifie_le = now() where id = 21415;
update contenu_questions set enonce = 'Que veut dire "dancing" en français ?', bonne_reponse = 'la danse', mauvais_choix = array['la natation','le dessin','la lecture'], modifie_le = now() where id = 21417;
update contenu_questions set enonce = 'Que veut dire "drawing" en français ?', bonne_reponse = 'le dessin', mauvais_choix = array['le chant','la course','la natation'], modifie_le = now() where id = 21419;
update contenu_questions set enonce = 'Comment dit-on "la lecture" en anglais ?', bonne_reponse = 'reading', mauvais_choix = array['drawing','basketball','cycling'], modifie_le = now() where id = 21420;
update contenu_questions set enonce = 'Que veut dire "reading" en français ?', bonne_reponse = 'la lecture', mauvais_choix = array['le basket','la course','le football'], modifie_le = now() where id = 21421;
update contenu_questions set enonce = 'Comment dit-on "le chant" en anglais ?', bonne_reponse = 'singing', mauvais_choix = array['swimming','basketball','running'], modifie_le = now() where id = 21422;
update contenu_questions set enonce = 'Que veut dire "singing" en français ?', bonne_reponse = 'le chant', mauvais_choix = array['la natation','la course','le dessin'], modifie_le = now() where id = 21423;
update contenu_questions set enonce = 'Comment dit-on "la course" en anglais ?', bonne_reponse = 'running', mauvais_choix = array['singing','basketball','dancing'], modifie_le = now() where id = 21424;
update contenu_questions set enonce = 'Que veut dire "running" en français ?', bonne_reponse = 'la course', mauvais_choix = array['la natation','le dessin','le basket'], modifie_le = now() where id = 21425;
update contenu_questions set enonce = 'Comment dit-on "le tennis" en anglais ?', bonne_reponse = 'tennis', mauvais_choix = array['football','reading','dancing'], modifie_le = now() where id = 21426;
update contenu_questions set enonce = 'Que veut dire "tennis" en français ?', bonne_reponse = 'le tennis', mauvais_choix = array['le dessin','la natation','le basket'], modifie_le = now() where id = 21427;
update contenu_questions set enonce = 'Comment dit-on "le basket" en anglais ?', bonne_reponse = 'basketball', mauvais_choix = array['cycling','reading','running'], modifie_le = now() where id = 21428;
update contenu_questions set enonce = 'Que veut dire "basketball" en français ?', bonne_reponse = 'le basket', mauvais_choix = array['le chant','la lecture','le dessin'], modifie_le = now() where id = 21429;
update contenu_questions set enonce = 'Comment dit-on "le golf" en anglais ?', bonne_reponse = 'golf', mauvais_choix = array['swimming','fishing','climbing'], modifie_le = now() where id = 21103;
update contenu_questions set enonce = 'Comment dit-on "l''équitation" en anglais ?', bonne_reponse = 'horse riding', mauvais_choix = array['climbing','judo','golf'], modifie_le = now() where id = 21129;
update contenu_questions set enonce = 'Comment dit-on "le tennis" en anglais ?', bonne_reponse = 'tennis', mauvais_choix = array['skiing','judo','horse riding'], modifie_le = now() where id = 21150;
update contenu_questions set enonce = 'Comment dit-on "le ski" en anglais ?', bonne_reponse = 'skiing', mauvais_choix = array['fishing','judo','golf'], modifie_le = now() where id = 21167;
update contenu_questions set enonce = 'Comment dit-on "la pêche" en anglais ?', bonne_reponse = 'fishing', mauvais_choix = array['skating','golf','skiing'], modifie_le = now() where id = 21175;
update contenu_questions set enonce = 'Comment dit-on "le judo" en anglais ?', bonne_reponse = 'judo', mauvais_choix = array['volleyball','swimming','skating'], modifie_le = now() where id = 21187;
update contenu_questions set enonce = 'Comment dit-on "le volley" en anglais ?', bonne_reponse = 'volleyball', mauvais_choix = array['golf','skiing','swimming'], modifie_le = now() where id = 21236;
update contenu_questions set enonce = 'Comment dit-on "un oiseau" en anglais ?', bonne_reponse = 'a bird', mauvais_choix = array['a duck','a dog','a horse'], modifie_le = now() where id = 18278;
update contenu_questions set enonce = 'Comment dit-on "un cheval" en anglais ?', bonne_reponse = 'a horse', mauvais_choix = array['a fish','a dog','a sheep'], modifie_le = now() where id = 18279;
update contenu_questions set enonce = 'Comment dit-on "une vache" en anglais ?', bonne_reponse = 'a cow', mauvais_choix = array['a cat','a duck','a sheep'], modifie_le = now() where id = 18280;
update contenu_questions set enonce = 'Comment dit-on "un cochon" en anglais ?', bonne_reponse = 'a pig', mauvais_choix = array['a bird','a rabbit','a cat'], modifie_le = now() where id = 18281;
update contenu_questions set enonce = 'Comment dit-on "un mouton" en anglais ?', bonne_reponse = 'a sheep', mauvais_choix = array['a cow','a bird','a cat'], modifie_le = now() where id = 18282;
update contenu_questions set enonce = 'Comment dit-on "un canard" en anglais ?', bonne_reponse = 'a duck', mauvais_choix = array['a mouse','a rabbit','a horse'], modifie_le = now() where id = 18283;
update contenu_questions set enonce = 'Comment dit-on "une grenouille" en anglais ?', bonne_reponse = 'a frog', mauvais_choix = array['a cow','a mouse','a fish'], modifie_le = now() where id = 18284;
update contenu_questions set enonce = 'Que veut dire "apples" en français ?', bonne_reponse = 'des pommes', mauvais_choix = array['des crayons','des règles','des chiens'], modifie_le = now() where id = 18336;
update contenu_questions set enonce = 'Que veut dire "bananas" en français ?', bonne_reponse = 'des bananes', mauvais_choix = array['des gommes','des chats','des crayons'], modifie_le = now() where id = 18338;
update contenu_questions set enonce = 'Que veut dire "eggs" en français ?', bonne_reponse = 'des oeufs', mauvais_choix = array['des lapins','des gommes','des bananes'], modifie_le = now() where id = 18340;
update contenu_questions set enonce = 'Que veut dire "cakes" en français ?', bonne_reponse = 'des gâteaux', mauvais_choix = array['des bananes','des pommes','des stylos'], modifie_le = now() where id = 18342;
update contenu_questions set enonce = 'Que veut dire "pencils" en français ?', bonne_reponse = 'des crayons', mauvais_choix = array['des stylos','des chiens','des règles'], modifie_le = now() where id = 18344;
update contenu_questions set enonce = 'Comment dit-on "des gommes" en anglais ?', bonne_reponse = 'rubbers', mauvais_choix = array['cats','rabbits','bananas'], modifie_le = now() where id = 18345;
update contenu_questions set enonce = 'Que veut dire "rubbers" en français ?', bonne_reponse = 'des gommes', mauvais_choix = array['des livres','des stylos','des bananes'], modifie_le = now() where id = 18346;
update contenu_questions set enonce = 'Comment dit-on "des règles" en anglais ?', bonne_reponse = 'rulers', mauvais_choix = array['dogs','pens','eggs'], modifie_le = now() where id = 18347;
update contenu_questions set enonce = 'Que veut dire "rulers" en français ?', bonne_reponse = 'des règles', mauvais_choix = array['des lapins','des chiens','des oeufs'], modifie_le = now() where id = 18348;
update contenu_questions set enonce = 'Comment dit-on "des livres" en anglais ?', bonne_reponse = 'books', mauvais_choix = array['cats','rulers','rabbits'], modifie_le = now() where id = 18349;
update contenu_questions set enonce = 'Que veut dire "books" en français ?', bonne_reponse = 'des livres', mauvais_choix = array['des lapins','des bananes','des crayons'], modifie_le = now() where id = 18350;
update contenu_questions set enonce = 'Comment dit-on "des stylos" en anglais ?', bonne_reponse = 'pens', mauvais_choix = array['rabbits','apples','books'], modifie_le = now() where id = 18351;
update contenu_questions set enonce = 'Que veut dire "pens" en français ?', bonne_reponse = 'des stylos', mauvais_choix = array['des règles','des lapins','des bananes'], modifie_le = now() where id = 18352;
update contenu_questions set enonce = 'Comment dit-on "des chats" en anglais ?', bonne_reponse = 'cats', mauvais_choix = array['books','pens','pencils'], modifie_le = now() where id = 18353;
update contenu_questions set enonce = 'Que veut dire "cats" en français ?', bonne_reponse = 'des chats', mauvais_choix = array['des chiens','des crayons','des pommes'], modifie_le = now() where id = 18354;
update contenu_questions set enonce = 'Comment dit-on "des chiens" en anglais ?', bonne_reponse = 'dogs', mauvais_choix = array['cats','pens','bananas'], modifie_le = now() where id = 18355;
update contenu_questions set enonce = 'Que veut dire "dogs" en français ?', bonne_reponse = 'des chiens', mauvais_choix = array['des règles','des bananes','des lapins'], modifie_le = now() where id = 18356;
update contenu_questions set enonce = 'Comment dit-on "des lapins" en anglais ?', bonne_reponse = 'rabbits', mauvais_choix = array['cats','rubbers','dogs'], modifie_le = now() where id = 18359;
update contenu_questions set enonce = 'Que veut dire "rabbits" en français ?', bonne_reponse = 'des lapins', mauvais_choix = array['des stylos','des chats','des crayons'], modifie_le = now() where id = 18360;
update contenu_questions set enonce = 'Comment dit-on "des pommes" en anglais ?', bonne_reponse = 'apples', mauvais_choix = array['rabbits','dogs','pens'], modifie_le = now() where id = 18369;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18370;
update contenu_questions set enonce = 'Comment dit-on "des bananes" en anglais ?', bonne_reponse = 'bananas', mauvais_choix = array['cats','rabbits','pencils'], modifie_le = now() where id = 18371;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18372;
update contenu_questions set enonce = 'Comment dit-on "des oeufs" en anglais ?', bonne_reponse = 'eggs', mauvais_choix = array['cats','dogs','rubbers'], modifie_le = now() where id = 18373;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18374;
update contenu_questions set enonce = 'Comment dit-on "des gâteaux" en anglais ?', bonne_reponse = 'cakes', mauvais_choix = array['eggs','pens','bananas'], modifie_le = now() where id = 18375;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18376;
update contenu_questions set enonce = 'Comment dit-on "des crayons" en anglais ?', bonne_reponse = 'pencils', mauvais_choix = array['apples','books','eggs'], modifie_le = now() where id = 18377;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18378;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18379;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18380;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18381;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18382;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18383;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18384;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18385;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18386;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18387;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18388;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18389;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18390;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18393;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18394;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18403;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18404;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18405;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18406;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18407;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18408;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18409;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18410;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18411;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18412;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18413;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18414;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18415;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18416;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18417;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18418;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18419;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18420;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18421;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18422;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18423;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18424;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18427;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18428;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18437;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18438;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18439;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18440;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18441;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18442;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18443;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18444;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18445;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18446;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18447;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18448;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18449;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18450;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18451;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18452;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18453;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18454;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18455;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18456;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18457;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18458;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18461;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18462;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18471;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18472;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18473;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18474;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18475;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18476;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18477;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18478;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18479;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18480;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18481;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18482;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18483;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18484;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18485;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18486;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18487;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18488;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18489;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18490;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18491;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18492;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18495;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18496;
update contenu_questions set enonce = 'Que veut dire "birds" en français ?', bonne_reponse = 'des oiseaux', mauvais_choix = array['des canards','des cochons','des vaches'], modifie_le = now() where id = 18358;
update contenu_questions set enonce = 'Que veut dire "cows" en français ?', bonne_reponse = 'des vaches', mauvais_choix = array['des grenouilles','des cochons','des canards'], modifie_le = now() where id = 18362;
update contenu_questions set enonce = 'Que veut dire "pigs" en français ?', bonne_reponse = 'des cochons', mauvais_choix = array['des canards','des grenouilles','des vaches'], modifie_le = now() where id = 18364;
update contenu_questions set enonce = 'Que veut dire "ducks" en français ?', bonne_reponse = 'des canards', mauvais_choix = array['des cochons','des grenouilles','des vaches'], modifie_le = now() where id = 18366;
update contenu_questions set enonce = 'Que veut dire "frogs" en français ?', bonne_reponse = 'des grenouilles', mauvais_choix = array['des vaches','des cochons','des canards'], modifie_le = now() where id = 18368;
update contenu_questions set enonce = 'Comment dit-on "des oiseaux" en anglais ?', bonne_reponse = 'birds', mauvais_choix = array['pigs','frogs','cows'], modifie_le = now() where id = 18391;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18392;
update contenu_questions set enonce = 'Comment dit-on "des vaches" en anglais ?', bonne_reponse = 'cows', mauvais_choix = array['pigs','ducks','birds'], modifie_le = now() where id = 18395;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18396;
update contenu_questions set enonce = 'Comment dit-on "des cochons" en anglais ?', bonne_reponse = 'pigs', mauvais_choix = array['frogs','cows','ducks'], modifie_le = now() where id = 18397;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18398;
update contenu_questions set enonce = 'Comment dit-on "des canards" en anglais ?', bonne_reponse = 'ducks', mauvais_choix = array['birds','cows','frogs'], modifie_le = now() where id = 18399;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18400;
update contenu_questions set enonce = 'Comment dit-on "des grenouilles" en anglais ?', bonne_reponse = 'frogs', mauvais_choix = array['ducks','birds','cows'], modifie_le = now() where id = 18401;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18402;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18425;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18426;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18429;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18430;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18431;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18432;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18433;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18434;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18435;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18436;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18459;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18460;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18463;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18464;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18465;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18466;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18467;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18468;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18469;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18470;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18493;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18494;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18497;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18498;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18499;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18500;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18501;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18502;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18503;
update contenu_questions set statut = 'archive', modifie_le = now() where id = 18504;
update contenu_questions set enonce = 'Comment dit-on "blanc" en anglais ?', bonne_reponse = 'white', mauvais_choix = array['red','orange','brown'], modifie_le = now() where id = 18261;
update contenu_questions set enonce = 'Comment dit-on "marron" en anglais ?', bonne_reponse = 'brown', mauvais_choix = array['yellow','green','purple'], modifie_le = now() where id = 18262;
update contenu_questions set enonce = 'Comment dit-on "rose" en anglais ?', bonne_reponse = 'pink', mauvais_choix = array['green','grey','red'], modifie_le = now() where id = 18263;
update contenu_questions set enonce = 'Comment dit-on "violet" en anglais ?', bonne_reponse = 'purple', mauvais_choix = array['blue','brown','yellow'], modifie_le = now() where id = 18264;
update contenu_questions set enonce = 'Comment dit-on "orange" en anglais ?', bonne_reponse = 'orange', mauvais_choix = array['blue','purple','red'], modifie_le = now() where id = 18265;
update contenu_questions set enonce = 'Comment dit-on "gris" en anglais ?', bonne_reponse = 'grey', mauvais_choix = array['black','yellow','orange'], modifie_le = now() where id = 18266;
update contenu_questions set enonce = 'Comment dit-on "le blanc" en anglais ?', bonne_reponse = 'white', mauvais_choix = array['red','sheep','fish'], modifie_le = now() where id = 18200;
update contenu_questions set enonce = 'Comment dit-on "le marron" en anglais ?', bonne_reponse = 'brown', mauvais_choix = array['white','red','black'], modifie_le = now() where id = 18202;
update contenu_questions set enonce = 'Comment dit-on "le rose" en anglais ?', bonne_reponse = 'pink', mauvais_choix = array['fish','black','blue'], modifie_le = now() where id = 18204;
update contenu_questions set enonce = 'Comment dit-on "le violet" en anglais ?', bonne_reponse = 'purple', mauvais_choix = array['mice','yellow','cheese'], modifie_le = now() where id = 18206;
update contenu_questions set enonce = 'Comment dit-on "l''orange" en anglais ?', bonne_reponse = 'orange', mauvais_choix = array['chocolate','cheese','bread'], modifie_le = now() where id = 18208;
update contenu_questions set enonce = 'Comment dit-on "le gris" en anglais ?', bonne_reponse = 'grey', mauvais_choix = array['blue','fish','milk'], modifie_le = now() where id = 18210;
update contenu_questions set enonce = 'Comment dit-on "le pain" en anglais ?', bonne_reponse = 'bread', mauvais_choix = array['juice','grey','purple'], modifie_le = now() where id = 18212;
update contenu_questions set enonce = 'Comment dit-on "le lait" en anglais ?', bonne_reponse = 'milk', mauvais_choix = array['white','pink','bread'], modifie_le = now() where id = 18214;
update contenu_questions set enonce = 'Comment dit-on "le fromage" en anglais ?', bonne_reponse = 'cheese', mauvais_choix = array['white','green','water'], modifie_le = now() where id = 18216;
update contenu_questions set enonce = 'Comment dit-on "le chocolat" en anglais ?', bonne_reponse = 'chocolate', mauvais_choix = array['juice','purple','yellow'], modifie_le = now() where id = 18218;
update contenu_questions set enonce = 'Comment dit-on "l''eau" en anglais ?', bonne_reponse = 'water', mauvais_choix = array['bread','purple','pink'], modifie_le = now() where id = 18220;
update contenu_questions set enonce = 'Comment dit-on "le jus de fruit" en anglais ?', bonne_reponse = 'juice', mauvais_choix = array['brown','fish','cheese'], modifie_le = now() where id = 18222;
update contenu_questions set enonce = 'Comment dit-on "les pommes" en anglais ?', bonne_reponse = 'apples', mauvais_choix = array['cows','dogs','horses'], modifie_le = now() where id = 18224;
update contenu_questions set enonce = 'Comment dit-on "les bananes" en anglais ?', bonne_reponse = 'bananas', mauvais_choix = array['horses','birds','cows'], modifie_le = now() where id = 18226;
update contenu_questions set enonce = 'Comment dit-on "les oeufs" en anglais ?', bonne_reponse = 'eggs', mauvais_choix = array['horses','frogs','bananas'], modifie_le = now() where id = 18228;
update contenu_questions set enonce = 'Comment dit-on "les gâteaux" en anglais ?', bonne_reponse = 'cakes', mauvais_choix = array['horses','frogs','bananas'], modifie_le = now() where id = 18230;
update contenu_questions set enonce = 'Comment dit-on "les chiens" en anglais ?', bonne_reponse = 'dogs', mauvais_choix = array['ducks','cows','birds'], modifie_le = now() where id = 18232;
update contenu_questions set enonce = 'Comment dit-on "les chats" en anglais ?', bonne_reponse = 'cats', mauvais_choix = array['horses','eggs','rabbits'], modifie_le = now() where id = 18234;
update contenu_questions set enonce = 'Comment dit-on "les souris" en anglais ?', bonne_reponse = 'mice', mauvais_choix = array['pink','grey','milk'], modifie_le = now() where id = 18236;
update contenu_questions set enonce = 'Comment dit-on "les lapins" en anglais ?', bonne_reponse = 'rabbits', mauvais_choix = array['apples','frogs','pigs'], modifie_le = now() where id = 18238;
update contenu_questions set enonce = 'Comment dit-on "les poissons" en anglais ?', bonne_reponse = 'fish', mauvais_choix = array['bread','blue','chocolate'], modifie_le = now() where id = 18240;
update contenu_questions set enonce = 'Comment dit-on "les oiseaux" en anglais ?', bonne_reponse = 'birds', mauvais_choix = array['eggs','cats','apples'], modifie_le = now() where id = 18242;
update contenu_questions set enonce = 'Comment dit-on "les chevaux" en anglais ?', bonne_reponse = 'horses', mauvais_choix = array['birds','pigs','rabbits'], modifie_le = now() where id = 18244;
update contenu_questions set enonce = 'Comment dit-on "les vaches" en anglais ?', bonne_reponse = 'cows', mauvais_choix = array['birds','eggs','pigs'], modifie_le = now() where id = 18246;
update contenu_questions set enonce = 'Comment dit-on "les cochons" en anglais ?', bonne_reponse = 'pigs', mauvais_choix = array['dogs','birds','frogs'], modifie_le = now() where id = 18248;
update contenu_questions set enonce = 'Comment dit-on "les moutons" en anglais ?', bonne_reponse = 'sheep', mauvais_choix = array['orange','blue','bread'], modifie_le = now() where id = 18250;
update contenu_questions set enonce = 'Comment dit-on "les canards" en anglais ?', bonne_reponse = 'ducks', mauvais_choix = array['cats','cakes','dogs'], modifie_le = now() where id = 18252;
update contenu_questions set enonce = 'Comment dit-on "les grenouilles" en anglais ?', bonne_reponse = 'frogs', mauvais_choix = array['cows','birds','pigs'], modifie_le = now() where id = 18254;
update contenu_questions set enonce = 'Comment dit-on "le blanc" en anglais ?', bonne_reponse = 'white', mauvais_choix = array['green','grey','black'], modifie_le = now() where id = 18201;
update contenu_questions set enonce = 'Comment dit-on "le marron" en anglais ?', bonne_reponse = 'brown', mauvais_choix = array['milk','black','sheep'], modifie_le = now() where id = 18203;
update contenu_questions set enonce = 'Comment dit-on "le rose" en anglais ?', bonne_reponse = 'pink', mauvais_choix = array['chocolate','milk','sheep'], modifie_le = now() where id = 18205;
update contenu_questions set enonce = 'Comment dit-on "le violet" en anglais ?', bonne_reponse = 'purple', mauvais_choix = array['yellow','water','pink'], modifie_le = now() where id = 18207;
update contenu_questions set enonce = 'Comment dit-on "l''orange" en anglais ?', bonne_reponse = 'orange', mauvais_choix = array['green','pink','grey'], modifie_le = now() where id = 18209;
update contenu_questions set enonce = 'Comment dit-on "le gris" en anglais ?', bonne_reponse = 'grey', mauvais_choix = array['cheese','milk','juice'], modifie_le = now() where id = 18211;
update contenu_questions set enonce = 'Comment dit-on "le pain" en anglais ?', bonne_reponse = 'bread', mauvais_choix = array['purple','blue','mice'], modifie_le = now() where id = 18213;
update contenu_questions set enonce = 'Comment dit-on "le lait" en anglais ?', bonne_reponse = 'milk', mauvais_choix = array['brown','orange','bread'], modifie_le = now() where id = 18215;
update contenu_questions set enonce = 'Comment dit-on "le fromage" en anglais ?', bonne_reponse = 'cheese', mauvais_choix = array['purple','milk','juice'], modifie_le = now() where id = 18217;
update contenu_questions set enonce = 'Comment dit-on "le chocolat" en anglais ?', bonne_reponse = 'chocolate', mauvais_choix = array['bread','cheese','grey'], modifie_le = now() where id = 18219;
update contenu_questions set enonce = 'Comment dit-on "l''eau" en anglais ?', bonne_reponse = 'water', mauvais_choix = array['sheep','black','grey'], modifie_le = now() where id = 18221;
update contenu_questions set enonce = 'Comment dit-on "le jus de fruit" en anglais ?', bonne_reponse = 'juice', mauvais_choix = array['water','milk','brown'], modifie_le = now() where id = 18223;
update contenu_questions set enonce = 'Comment dit-on "les pommes" en anglais ?', bonne_reponse = 'apples', mauvais_choix = array['frogs','cats','pigs'], modifie_le = now() where id = 18225;
update contenu_questions set enonce = 'Comment dit-on "les bananes" en anglais ?', bonne_reponse = 'bananas', mauvais_choix = array['pigs','cows','ducks'], modifie_le = now() where id = 18227;
update contenu_questions set enonce = 'Comment dit-on "les oeufs" en anglais ?', bonne_reponse = 'eggs', mauvais_choix = array['pigs','horses','apples'], modifie_le = now() where id = 18229;
update contenu_questions set enonce = 'Comment dit-on "les gâteaux" en anglais ?', bonne_reponse = 'cakes', mauvais_choix = array['pigs','rabbits','horses'], modifie_le = now() where id = 18231;
update contenu_questions set enonce = 'Comment dit-on "les chiens" en anglais ?', bonne_reponse = 'dogs', mauvais_choix = array['rabbits','pigs','ducks'], modifie_le = now() where id = 18233;
update contenu_questions set enonce = 'Comment dit-on "les chats" en anglais ?', bonne_reponse = 'cats', mauvais_choix = array['frogs','rabbits','apples'], modifie_le = now() where id = 18235;
update contenu_questions set enonce = 'Comment dit-on "les souris" en anglais ?', bonne_reponse = 'mice', mauvais_choix = array['orange','water','green'], modifie_le = now() where id = 18237;
update contenu_questions set enonce = 'Comment dit-on "les lapins" en anglais ?', bonne_reponse = 'rabbits', mauvais_choix = array['horses','eggs','frogs'], modifie_le = now() where id = 18239;
update contenu_questions set enonce = 'Comment dit-on "les poissons" en anglais ?', bonne_reponse = 'fish', mauvais_choix = array['red','bread','green'], modifie_le = now() where id = 18241;
update contenu_questions set enonce = 'Comment dit-on "les oiseaux" en anglais ?', bonne_reponse = 'birds', mauvais_choix = array['cakes','cows','horses'], modifie_le = now() where id = 18243;
update contenu_questions set enonce = 'Comment dit-on "les chevaux" en anglais ?', bonne_reponse = 'horses', mauvais_choix = array['apples','pigs','dogs'], modifie_le = now() where id = 18245;
update contenu_questions set enonce = 'Comment dit-on "les vaches" en anglais ?', bonne_reponse = 'cows', mauvais_choix = array['bananas','dogs','pigs'], modifie_le = now() where id = 18247;
update contenu_questions set enonce = 'Comment dit-on "les cochons" en anglais ?', bonne_reponse = 'pigs', mauvais_choix = array['eggs','cats','dogs'], modifie_le = now() where id = 18249;
update contenu_questions set enonce = 'Comment dit-on "les moutons" en anglais ?', bonne_reponse = 'sheep', mauvais_choix = array['white','green','grey'], modifie_le = now() where id = 18251;
update contenu_questions set enonce = 'Comment dit-on "les canards" en anglais ?', bonne_reponse = 'ducks', mauvais_choix = array['birds','cakes','cats'], modifie_le = now() where id = 18253;
update contenu_questions set enonce = 'Comment dit-on "les grenouilles" en anglais ?', bonne_reponse = 'frogs', mauvais_choix = array['cakes','horses','bananas'], modifie_le = now() where id = 18255;
update contenu_questions set enonce = replace(enonce, 'a elephant', 'an elephant'), bonne_reponse = replace(bonne_reponse, 'a elephant', 'an elephant'), mauvais_choix = (select array_agg(replace(x, 'a elephant', 'an elephant')) from unnest(mauvais_choix) x), modifie_le = now() where matiere = 'english' and statut = 'publie' and (enonce || bonne_reponse || array_to_string(mauvais_choix, '|')) ~ '\ma elephant';
commit;
select fn_publier();
