-- AUDITS_LOG #33 (2026-10-03) : mauvaises reponses refaites (sujet du verbe CE2, pluriel des noms CE1 grammaire).
begin;
update contenu_questions set bonne_reponse = 'le chat', mauvais_choix = array['mange','la souris','mange la souris'], modifie_le = now() where id = 10010;
update contenu_questions set bonne_reponse = 'les enfants', mauvais_choix = array['jouent','dans le jardin','jouent dans le jardin'], modifie_le = now() where id = 10011;
update contenu_questions set bonne_reponse = 'ma mère', mauvais_choix = array['prépare','le repas','prépare le repas'], modifie_le = now() where id = 10012;
update contenu_questions set bonne_reponse = 'les oiseaux', mauvais_choix = array['chantent','le matin','chantent le matin'], modifie_le = now() where id = 10013;
update contenu_questions set bonne_reponse = 'le vent', mauvais_choix = array['souffle','fort','souffle fort'], modifie_le = now() where id = 10014;
update contenu_questions set bonne_reponse = 'les élèves', mauvais_choix = array['écoutent','la maîtresse','écoutent la maîtresse'], modifie_le = now() where id = 10015;
update contenu_questions set bonne_reponse = 'mon frère', mauvais_choix = array['lit','un livre','lit un livre'], modifie_le = now() where id = 10016;
update contenu_questions set bonne_reponse = 'la pluie', mauvais_choix = array['tombe','sur la ville','tombe sur la ville'], modifie_le = now() where id = 10017;
update contenu_questions set bonne_reponse = 'les voitures', mauvais_choix = array['roulent','vite','roulent vite'], modifie_le = now() where id = 10018;
update contenu_questions set bonne_reponse = 'le soleil', mauvais_choix = array['brille','aujourd''hui','brille aujourd''hui'], modifie_le = now() where id = 10019;
update contenu_questions set bonne_reponse = 'bocaux', mauvais_choix = array['bocals','bocaus','boceaux'], modifie_le = now() where id = 28000;
update contenu_questions set bonne_reponse = 'locaux', mauvais_choix = array['locals','locaus','loceaux'], modifie_le = now() where id = 28001;
update contenu_questions set bonne_reponse = 'métaux', mauvais_choix = array['métals','métaus','méteaux'], modifie_le = now() where id = 28002;
update contenu_questions set bonne_reponse = 'minéraux', mauvais_choix = array['minérals','minéraus','minéreaux'], modifie_le = now() where id = 28003;
update contenu_questions set bonne_reponse = 'végétaux', mauvais_choix = array['végétals','végétaus','végéteaux'], modifie_le = now() where id = 28004;
update contenu_questions set bonne_reponse = 'maux', mauvais_choix = array['mals','maus','meaux'], modifie_le = now() where id = 28005;
update contenu_questions set bonne_reponse = 'travaux', mauvais_choix = array['travails','travaus','traveaux'], modifie_le = now() where id = 28006;
update contenu_questions set bonne_reponse = 'coraux', mauvais_choix = array['corails','coraus','coreaux'], modifie_le = now() where id = 28007;
update contenu_questions set bonne_reponse = 'gaz', mauvais_choix = array['gazs','gas','gazes'], modifie_le = now() where id = 28008;
update contenu_questions set bonne_reponse = 'radis', mauvais_choix = array['radix','radises','radi'], modifie_le = now() where id = 28009;
update contenu_questions set bonne_reponse = 'avis', mauvais_choix = array['avix','avises','avi'], modifie_le = now() where id = 28010;
update contenu_questions set bonne_reponse = 'repas', mauvais_choix = array['repax','repases','repa'], modifie_le = now() where id = 28011;
update contenu_questions set bonne_reponse = 'permis', mauvais_choix = array['permix','permises','permi'], modifie_le = now() where id = 28012;
update contenu_questions set bonne_reponse = 'puits', mauvais_choix = array['puitx','puitses','puit'], modifie_le = now() where id = 28013;
update contenu_questions set bonne_reponse = 'matelas', mauvais_choix = array['matelax','matelases','matela'], modifie_le = now() where id = 28014;
update contenu_questions set bonne_reponse = 'ours', mauvais_choix = array['ourx','ourses','our'], modifie_le = now() where id = 28015;
update contenu_questions set bonne_reponse = 'dos', mauvais_choix = array['dox','doses','do'], modifie_le = now() where id = 28016;
update contenu_questions set bonne_reponse = 'choix', mauvais_choix = array['chois','choixes','choi'], modifie_le = now() where id = 28017;
update contenu_questions set bonne_reponse = 'corps', mauvais_choix = array['corpx','corpses','corp'], modifie_le = now() where id = 28783;
update contenu_questions set bonne_reponse = 'musiciens', mauvais_choix = array['musicien','musicienes','musicienx'], modifie_le = now() where id = 28784;
update contenu_questions set bonne_reponse = 'médailles', mauvais_choix = array['médaille','médaillex','médaills'], modifie_le = now() where id = 28785;
update contenu_questions set bonne_reponse = 'photographes', mauvais_choix = array['photographe','photographex','photographs'], modifie_le = now() where id = 28786;
update contenu_questions set bonne_reponse = 'satellites', mauvais_choix = array['satellite','satellitex','satellits'], modifie_le = now() where id = 28787;
update contenu_questions set bonne_reponse = 'niveaux', mauvais_choix = array['niveaus','niveau','nivaux'], modifie_le = now() where id = 28788;
update contenu_questions set bonne_reponse = 'robinets', mauvais_choix = array['robinet','robinetes','robinetx'], modifie_le = now() where id = 28789;
update contenu_questions set bonne_reponse = 'planètes', mauvais_choix = array['planète','planètex','planèts'], modifie_le = now() where id = 28790;
update contenu_questions set bonne_reponse = 'boulangers', mauvais_choix = array['boulanger','boulangeres','boulangerx'], modifie_le = now() where id = 28791;
update contenu_questions set bonne_reponse = 'trousses', mauvais_choix = array['trousse','troussex','trousss'], modifie_le = now() where id = 28792;
update contenu_questions set bonne_reponse = 'panneaux', mauvais_choix = array['panneaus','panneau','pannaux'], modifie_le = now() where id = 28793;
update contenu_questions set bonne_reponse = 'canapés', mauvais_choix = array['canapé','canapéx','canapées'], modifie_le = now() where id = 28794;
update contenu_questions set bonne_reponse = 'secours', mauvais_choix = array['secourx','secourses','secour'], modifie_le = now() where id = 28795;
update contenu_questions set bonne_reponse = 'escaliers', mauvais_choix = array['escalier','escalieres','escalierx'], modifie_le = now() where id = 28796;
update contenu_questions set bonne_reponse = 'morceaux', mauvais_choix = array['morceaus','morceau','morcaux'], modifie_le = now() where id = 28797;
update contenu_questions set bonne_reponse = 'succès', mauvais_choix = array['succèx','succèses','succè'], modifie_le = now() where id = 28798;
update contenu_questions set bonne_reponse = 'balcons', mauvais_choix = array['balcon','balcones','balconx'], modifie_le = now() where id = 28799;
update contenu_questions set bonne_reponse = 'roseaux', mauvais_choix = array['roseaus','roseau','rosaux'], modifie_le = now() where id = 28800;
update contenu_questions set bonne_reponse = 'fantômes', mauvais_choix = array['fantôme','fantômex','fantôms'], modifie_le = now() where id = 28801;
update contenu_questions set bonne_reponse = 'carreaux', mauvais_choix = array['carreaus','carreau','carraux'], modifie_le = now() where id = 28802;
update contenu_questions set bonne_reponse = 'serveurs', mauvais_choix = array['serveur','serveures','serveurx'], modifie_le = now() where id = 28803;
update contenu_questions set bonne_reponse = 'facteurs', mauvais_choix = array['facteur','facteures','facteurx'], modifie_le = now() where id = 28804;
update contenu_questions set bonne_reponse = 'oiseaux', mauvais_choix = array['oiseaus','oiseau','oisaux'], modifie_le = now() where id = 28805;
update contenu_questions set bonne_reponse = 'boussoles', mauvais_choix = array['boussole','boussolex','boussols'], modifie_le = now() where id = 28806;
update contenu_questions set bonne_reponse = 'peignes', mauvais_choix = array['peigne','peignex','peigns'], modifie_le = now() where id = 28807;
update contenu_questions set bonne_reponse = 'lutins', mauvais_choix = array['lutin','lutines','lutinx'], modifie_le = now() where id = 28808;
update contenu_questions set bonne_reponse = 'peintres', mauvais_choix = array['peintre','peintrex','peintrs'], modifie_le = now() where id = 28809;
update contenu_questions set bonne_reponse = 'toits', mauvais_choix = array['toit','toites','toitx'], modifie_le = now() where id = 28810;
update contenu_questions set bonne_reponse = 'fauteuils', mauvais_choix = array['fauteuil','fauteuiles','fauteuilx'], modifie_le = now() where id = 28811;
update contenu_questions set bonne_reponse = 'dragons', mauvais_choix = array['dragon','dragones','dragonx'], modifie_le = now() where id = 28812;
update contenu_questions set bonne_reponse = 'robots', mauvais_choix = array['robot','robotes','robotx'], modifie_le = now() where id = 28813;
update contenu_questions set bonne_reponse = 'fusées', mauvais_choix = array['fusée','fuséex','fusés'], modifie_le = now() where id = 28814;
update contenu_questions set bonne_reponse = 'réseaux', mauvais_choix = array['réseaus','réseau','résaux'], modifie_le = now() where id = 28815;
update contenu_questions set bonne_reponse = 'trophées', mauvais_choix = array['trophée','trophéex','trophés'], modifie_le = now() where id = 28816;
update contenu_questions set bonne_reponse = 'savons', mauvais_choix = array['savon','savones','savonx'], modifie_le = now() where id = 28817;
update contenu_questions set bonne_reponse = 'caissiers', mauvais_choix = array['caissier','caissieres','caissierx'], modifie_le = now() where id = 28818;
update contenu_questions set bonne_reponse = 'refus', mauvais_choix = array['refux','refuses','refu'], modifie_le = now() where id = 28819;
update contenu_questions set bonne_reponse = 'drapeaux', mauvais_choix = array['drapeaus','drapeau','drapaux'], modifie_le = now() where id = 28820;
update contenu_questions set bonne_reponse = 'chevaliers', mauvais_choix = array['chevalier','chevalieres','chevalierx'], modifie_le = now() where id = 28821;
update contenu_questions set bonne_reponse = 'cartables', mauvais_choix = array['cartable','cartablex','cartabls'], modifie_le = now() where id = 28822;
update contenu_questions set bonne_reponse = 'mon père', mauvais_choix = array['travaille','dur','travaille dur'], modifie_le = now() where id = 31043;
update contenu_questions set bonne_reponse = 'la maîtresse', mauvais_choix = array['explique','la leçon','explique la leçon'], modifie_le = now() where id = 31044;
update contenu_questions set bonne_reponse = 'les chiens', mauvais_choix = array['aboient','fort','aboient fort'], modifie_le = now() where id = 31045;
update contenu_questions set bonne_reponse = 'le facteur', mauvais_choix = array['distribue','le courrier','distribue le courrier'], modifie_le = now() where id = 31046;
update contenu_questions set bonne_reponse = 'les fleurs', mauvais_choix = array['poussent','au printemps','poussent au printemps'], modifie_le = now() where id = 31047;
update contenu_questions set bonne_reponse = 'le fermier', mauvais_choix = array['cultive','son champ','cultive son champ'], modifie_le = now() where id = 31048;
update contenu_questions set bonne_reponse = 'les nuages', mauvais_choix = array['cachent','le soleil','cachent le soleil'], modifie_le = now() where id = 31049;
update contenu_questions set bonne_reponse = 'la rivière', mauvais_choix = array['coule','doucement','coule doucement'], modifie_le = now() where id = 31050;
update contenu_questions set bonne_reponse = 'le vélo', mauvais_choix = array['roule','vite','roule vite'], modifie_le = now() where id = 31051;
update contenu_questions set bonne_reponse = 'les avions', mauvais_choix = array['décollent','à midi','décollent à midi'], modifie_le = now() where id = 31052;
update contenu_questions set bonne_reponse = 'le train', mauvais_choix = array['arrive','en retard','arrive en retard'], modifie_le = now() where id = 31053;
update contenu_questions set bonne_reponse = 'ma soeur', mauvais_choix = array['dessine','un chat','dessine un chat'], modifie_le = now() where id = 31054;
update contenu_questions set bonne_reponse = 'les poissons', mauvais_choix = array['nagent','dans l''étang','nagent dans l''étang'], modifie_le = now() where id = 31055;
update contenu_questions set bonne_reponse = 'le jardinier', mauvais_choix = array['plante','des fleurs','plante des fleurs'], modifie_le = now() where id = 31056;
update contenu_questions set bonne_reponse = 'les abeilles', mauvais_choix = array['butinent','les fleurs','butinent les fleurs'], modifie_le = now() where id = 31057;
update contenu_questions set bonne_reponse = 'le boulanger', mauvais_choix = array['vend','du pain','vend du pain'], modifie_le = now() where id = 31058;
update contenu_questions set bonne_reponse = 'la neige', mauvais_choix = array['tombe','en hiver','tombe en hiver'], modifie_le = now() where id = 31059;
update contenu_questions set bonne_reponse = 'les feuilles', mauvais_choix = array['tombent','en automne','tombent en automne'], modifie_le = now() where id = 31060;
update contenu_questions set bonne_reponse = 'le bateau', mauvais_choix = array['navigue','sur le lac','navigue sur le lac'], modifie_le = now() where id = 31061;
update contenu_questions set bonne_reponse = 'les étoiles', mauvais_choix = array['brillent','la nuit','brillent la nuit'], modifie_le = now() where id = 31062;
update contenu_questions set bonne_reponse = 'le renard', mauvais_choix = array['court','dans la forêt','court dans la forêt'], modifie_le = now() where id = 31208;
update contenu_questions set bonne_reponse = 'la biche', mauvais_choix = array['broute','l''herbe','broute l''herbe'], modifie_le = now() where id = 31209;
update contenu_questions set bonne_reponse = 'les lapins', mauvais_choix = array['creusent','un terrier','creusent un terrier'], modifie_le = now() where id = 31210;
update contenu_questions set bonne_reponse = 'mon cousin', mauvais_choix = array['répare','son vélo','répare son vélo'], modifie_le = now() where id = 31211;
update contenu_questions set bonne_reponse = 'ma cousine', mauvais_choix = array['lit','un magazine','lit un magazine'], modifie_le = now() where id = 31212;
update contenu_questions set bonne_reponse = 'les pêcheurs', mauvais_choix = array['attrapent','des poissons','attrapent des poissons'], modifie_le = now() where id = 31213;
update contenu_questions set bonne_reponse = 'le boulanger', mauvais_choix = array['vend','des croissants','vend des croissants'], modifie_le = now() where id = 31214;
update contenu_questions set bonne_reponse = 'la fleuriste', mauvais_choix = array['vend','des bouquets','vend des bouquets'], modifie_le = now() where id = 31215;
update contenu_questions set bonne_reponse = 'les tortues', mauvais_choix = array['nagent','lentement','nagent lentement'], modifie_le = now() where id = 31216;
update contenu_questions set bonne_reponse = 'le dauphin', mauvais_choix = array['saute','hors de l''eau','saute hors de l''eau'], modifie_le = now() where id = 31217;
update contenu_questions set bonne_reponse = 'les fourmis', mauvais_choix = array['transportent','des graines','transportent des graines'], modifie_le = now() where id = 31218;
update contenu_questions set bonne_reponse = 'la coccinelle', mauvais_choix = array['vole','de fleur en fleur','vole de fleur en fleur'], modifie_le = now() where id = 31219;
update contenu_questions set bonne_reponse = 'le loup', mauvais_choix = array['hurle','la nuit','hurle la nuit'], modifie_le = now() where id = 31220;
update contenu_questions set bonne_reponse = 'les moutons', mauvais_choix = array['broutent','dans le pré','broutent dans le pré'], modifie_le = now() where id = 31221;
update contenu_questions set bonne_reponse = 'la chèvre', mauvais_choix = array['broute','l''herbe du pré','broute l''herbe du pré'], modifie_le = now() where id = 31222;
update contenu_questions set bonne_reponse = 'le berger', mauvais_choix = array['garde','le troupeau','garde le troupeau'], modifie_le = now() where id = 31223;
update contenu_questions set bonne_reponse = 'la libellule', mauvais_choix = array['vole','doucement','vole doucement'], modifie_le = now() where id = 31224;
update contenu_questions set bonne_reponse = 'le hérisson', mauvais_choix = array['se cache','sous les feuilles','se cache sous les feuilles'], modifie_le = now() where id = 31225;
update contenu_questions set bonne_reponse = 'les papillons', mauvais_choix = array['volent','au-dessus du jardin','volent au-dessus du jardin'], modifie_le = now() where id = 31226;
update contenu_questions set bonne_reponse = 'le jardinier', mauvais_choix = array['plante','des légumes','plante des légumes'], modifie_le = now() where id = 31227;
update contenu_questions set bonne_reponse = 'la cuisinière', mauvais_choix = array['prépare','le dîner','prépare le dîner'], modifie_le = now() where id = 31228;
update contenu_questions set bonne_reponse = 'les musiciens', mauvais_choix = array['jouent','une mélodie','jouent une mélodie'], modifie_le = now() where id = 31229;
update contenu_questions set bonne_reponse = 'le peintre', mauvais_choix = array['peint','un tableau','peint un tableau'], modifie_le = now() where id = 31230;
update contenu_questions set bonne_reponse = 'la danseuse', mauvais_choix = array['danse','sur scène','danse sur scène'], modifie_le = now() where id = 31231;
update contenu_questions set bonne_reponse = 'les chanteurs', mauvais_choix = array['chantent','en choeur','chantent en choeur'], modifie_le = now() where id = 31232;
update contenu_questions set bonne_reponse = 'le sportif', mauvais_choix = array['court','le marathon','court le marathon'], modifie_le = now() where id = 31233;
update contenu_questions set bonne_reponse = 'la nageuse', mauvais_choix = array['nage','dans la piscine','nage dans la piscine'], modifie_le = now() where id = 31234;
update contenu_questions set bonne_reponse = 'les cyclistes', mauvais_choix = array['roulent','vite','roulent vite'], modifie_le = now() where id = 31235;
update contenu_questions set bonne_reponse = 'le coureur', mauvais_choix = array['gagne','la course','gagne la course'], modifie_le = now() where id = 31236;
update contenu_questions set bonne_reponse = 'les élèves', mauvais_choix = array['rangent','leurs cahiers','rangent leurs cahiers'], modifie_le = now() where id = 31772;
update contenu_questions set bonne_reponse = 'le boucher', mauvais_choix = array['coupe','la viande','coupe la viande'], modifie_le = now() where id = 31773;
update contenu_questions set bonne_reponse = 'le pâtissier', mauvais_choix = array['prépare','des croissants','prépare des croissants'], modifie_le = now() where id = 31774;
update contenu_questions set bonne_reponse = 'la coccinelle', mauvais_choix = array['grimpe','sur la tige','grimpe sur la tige'], modifie_le = now() where id = 31775;
update contenu_questions set bonne_reponse = 'les truites', mauvais_choix = array['nagent','dans le ruisseau','nagent dans le ruisseau'], modifie_le = now() where id = 31776;
update contenu_questions set bonne_reponse = 'le dragon', mauvais_choix = array['garde','le trésor','garde le trésor'], modifie_le = now() where id = 31777;
update contenu_questions set bonne_reponse = 'le bus', mauvais_choix = array['s''arrête','devant l''école','s''arrête devant l''école'], modifie_le = now() where id = 31778;
update contenu_questions set bonne_reponse = 'le pompier', mauvais_choix = array['éteint','l''incendie','éteint l''incendie'], modifie_le = now() where id = 31779;
update contenu_questions set bonne_reponse = 'le paysan', mauvais_choix = array['laboure','son champ','laboure son champ'], modifie_le = now() where id = 31780;
update contenu_questions set bonne_reponse = 'les castors', mauvais_choix = array['construisent','un barrage','construisent un barrage'], modifie_le = now() where id = 31781;
update contenu_questions set bonne_reponse = 'les nuages', mauvais_choix = array['annoncent','la pluie','annoncent la pluie'], modifie_le = now() where id = 31782;
update contenu_questions set bonne_reponse = 'la brume', mauvais_choix = array['recouvre','la vallée','recouvre la vallée'], modifie_le = now() where id = 31783;
update contenu_questions set bonne_reponse = 'les phoques', mauvais_choix = array['plongent','dans l''eau glacée','plongent dans l''eau glacée'], modifie_le = now() where id = 31784;
update contenu_questions set bonne_reponse = 'le chat', mauvais_choix = array['miaule','devant la porte','miaule devant la porte'], modifie_le = now() where id = 31785;
update contenu_questions set bonne_reponse = 'les cigognes', mauvais_choix = array['reviennent','chaque année','reviennent chaque année'], modifie_le = now() where id = 31786;
update contenu_questions set bonne_reponse = 'les fourmis', mauvais_choix = array['transportent','une feuille','transportent une feuille'], modifie_le = now() where id = 31787;
update contenu_questions set bonne_reponse = 'le vent', mauvais_choix = array['agite','les branches','agite les branches'], modifie_le = now() where id = 31788;
update contenu_questions set bonne_reponse = 'les abeilles', mauvais_choix = array['retournent','à la ruche','retournent à la ruche'], modifie_le = now() where id = 31789;
update contenu_questions set bonne_reponse = 'le professeur', mauvais_choix = array['explique','la leçon','explique la leçon'], modifie_le = now() where id = 31790;
update contenu_questions set bonne_reponse = 'le facteur', mauvais_choix = array['sonne','à la porte','sonne à la porte'], modifie_le = now() where id = 31791;
update contenu_questions set bonne_reponse = 'le berger', mauvais_choix = array['guide','son troupeau','guide son troupeau'], modifie_le = now() where id = 31792;
update contenu_questions set bonne_reponse = 'les hérissons', mauvais_choix = array['se cachent','sous les feuilles','se cachent sous les feuilles'], modifie_le = now() where id = 31793;
update contenu_questions set bonne_reponse = 'les feuilles', mauvais_choix = array['jaunissent','en automne','jaunissent en automne'], modifie_le = now() where id = 31794;
update contenu_questions set bonne_reponse = 'les randonneurs', mauvais_choix = array['traversent','le pont','traversent le pont'], modifie_le = now() where id = 31795;
update contenu_questions set bonne_reponse = 'les sirènes', mauvais_choix = array['chantent','dans la mer','chantent dans la mer'], modifie_le = now() where id = 31796;
update contenu_questions set bonne_reponse = 'le magicien', mauvais_choix = array['réalise','un tour','réalise un tour'], modifie_le = now() where id = 31797;
update contenu_questions set bonne_reponse = 'le hibou', mauvais_choix = array['chasse','la nuit','chasse la nuit'], modifie_le = now() where id = 31798;
update contenu_questions set bonne_reponse = 'le prince', mauvais_choix = array['libère','la princesse','libère la princesse'], modifie_le = now() where id = 31799;
update contenu_questions set bonne_reponse = 'la sorcière', mauvais_choix = array['prépare','une potion','prépare une potion'], modifie_le = now() where id = 31800;
update contenu_questions set bonne_reponse = 'les explorateurs', mauvais_choix = array['traversent','le désert','traversent le désert'], modifie_le = now() where id = 31801;
update contenu_questions set bonne_reponse = 'le clown', mauvais_choix = array['fait','rire les enfants','fait rire les enfants'], modifie_le = now() where id = 31802;
update contenu_questions set bonne_reponse = 'le vieux chêne', mauvais_choix = array['perd','ses feuilles','perd ses feuilles'], modifie_le = now() where id = 31803;
update contenu_questions set bonne_reponse = 'le chevalier', mauvais_choix = array['porte','une armure','porte une armure'], modifie_le = now() where id = 31804;
update contenu_questions set bonne_reponse = 'les moineaux', mauvais_choix = array['picorent','des graines','picorent des graines'], modifie_le = now() where id = 31805;
update contenu_questions set bonne_reponse = 'ma tante', mauvais_choix = array['peint','un tableau','peint un tableau'], modifie_le = now() where id = 31806;
update contenu_questions set bonne_reponse = 'les castors', mauvais_choix = array['rongent','le tronc','rongent le tronc'], modifie_le = now() where id = 31807;
update contenu_questions set bonne_reponse = 'la reine', mauvais_choix = array['dirige','son royaume','dirige son royaume'], modifie_le = now() where id = 31808;
update contenu_questions set bonne_reponse = 'le champion', mauvais_choix = array['lève','la coupe','lève la coupe'], modifie_le = now() where id = 31809;
update contenu_questions set bonne_reponse = 'canaux', mauvais_choix = array['canals','canaus','caneaux'], modifie_le = now() where id = 100067;
update contenu_questions set bonne_reponse = 'généraux', mauvais_choix = array['générals','généraus','généreaux'], modifie_le = now() where id = 100068;
update contenu_questions set bonne_reponse = 'hôpitaux', mauvais_choix = array['hôpitals','hôpitaus','hôpiteaux'], modifie_le = now() where id = 100069;
update contenu_questions set bonne_reponse = 'tribunaux', mauvais_choix = array['tribunals','tribunaus','tribuneaux'], modifie_le = now() where id = 100070;
update contenu_questions set bonne_reponse = 'chevaux', mauvais_choix = array['chevals','chevaus','cheveaux'], modifie_le = now() where id = 100071;
update contenu_questions set bonne_reponse = 'journaux', mauvais_choix = array['journals','journaus','journeaux'], modifie_le = now() where id = 100072;
update contenu_questions set bonne_reponse = 'animaux', mauvais_choix = array['animals','animaus','animeaux'], modifie_le = now() where id = 100073;
update contenu_questions set bonne_reponse = 'signaux', mauvais_choix = array['signals','signaus','signeaux'], modifie_le = now() where id = 100074;
update contenu_questions set bonne_reponse = 'bras', mauvais_choix = array['brax','brases','bra'], modifie_le = now() where id = 100075;
update contenu_questions set bonne_reponse = 'souris', mauvais_choix = array['sourix','sourises','souri'], modifie_le = now() where id = 100076;
update contenu_questions set bonne_reponse = 'tapis', mauvais_choix = array['tapix','tapises','tapi'], modifie_le = now() where id = 100077;
update contenu_questions set bonne_reponse = 'croix', mauvais_choix = array['crois','croixes','croi'], modifie_le = now() where id = 100078;
update contenu_questions set bonne_reponse = 'voix', mauvais_choix = array['vois','voixes','voi'], modifie_le = now() where id = 100079;
update contenu_questions set bonne_reponse = 'fils', mauvais_choix = array['filx','filses','fil'], modifie_le = now() where id = 100080;
update contenu_questions set bonne_reponse = 'pays', mauvais_choix = array['payx','payses','pay'], modifie_le = now() where id = 100081;
update contenu_questions set bonne_reponse = 'nez', mauvais_choix = array['nezs','nes','nezes'], modifie_le = now() where id = 100082;
update contenu_questions set bonne_reponse = 'temps', mauvais_choix = array['tempx','tempses','temp'], modifie_le = now() where id = 100083;
update contenu_questions set bonne_reponse = 'prix', mauvais_choix = array['pris','prixes','pri'], modifie_le = now() where id = 100084;
commit;
select fn_publier();
