-- ============================================================================
-- NOTIONS - étape 1/3 : structure (2026-09-27)
-- Ajoute la table contenu_notions et la colonne notion_id sur les questions et les fiches.
-- Ne touche à AUCUNE table de comptes joueurs. Ne supprime aucune question.
-- Une notion est commune à toutes les classes ; c'est la colonne "classe" de la question
-- (ou de la fiche) qui porte le niveau. Une fiche = une notion + une classe.
-- ============================================================================
begin;

-- 1. Table des notions
create table contenu_notions (
	id integer primary key generated by default as identity,
	code text not null unique check (code ~ '^[a-z0-9_]+$'),
	libelle text not null check (length(trim(libelle)) > 0),
	domaine text not null check (domaine in ('Maths', 'Français', 'Lecture', 'Logique', 'Anglais')),
	ordre integer not null default 0,
	cree_le timestamptz not null default now(),
	modifie_le timestamptz not null default now()
);
alter table contenu_notions enable row level security;
create trigger trace_notions before update or delete on contenu_notions
	for each row execute function fn_contenu_trace();

-- 2. Chaque question sera rattachée à une notion (rendu obligatoire à l'étape 2, une fois rempli)
alter table contenu_questions add column notion_id integer references contenu_notions (id);
create index contenu_questions_notion_idx on contenu_questions (notion_id, classe);

-- 3. Fiches de cours : rattachées à une notion ; une seule fiche active par notion + classe
alter table contenu_cours add column notion_id integer references contenu_notions (id);
create unique index contenu_cours_notion_classe_idx on contenu_cours (notion_id, classe) where statut <> 'archive';

commit;
