# Reserve de mots courants de niveau CM1/CM2 presentant une difficulte d'orthographe
# (consonne doublee, m devant b/p, accents, -tion, lettres muettes, h, ph, y, ill...).
# Seuls les mots presents dans le dictionnaire et absents de la classe sont utilises.
MOTS = """
abeille abricot absence absent accent accepter accompagner accord accrobate accueil acheter acrobate addition adorable adresse aéroport affaire affiche affreux agneau aiguille aimable album alphabet allumette alouette ambulance amitié ampoule ancêtre animal anniversaire annonce appareil appartement appel appétit applaudir apporter apprendre appuyer après-midi aquarium araignée arbitre architecte argent armoire arracher arrêter arrivée arrosoir artichaut ascenseur aspirateur assiette assis athlète attacher attendre attention attraper aubergine autobus automne autoroute autruche avalanche avenir aventure averse aveugle avion avocat
bagage baguette baignoire balançoire balayer baleine ballerine banane bandeau banquette barrière bassin bâtiment bâton battre bavarder beignet bergère besoin bibliothèque bicyclette bijou billet biscuit blessure blouson boisson bonhomme bonheur bonnet bottes bouchon boucle bouillir boulanger boussole bouteille boutique bracelet branche brindille brioche brouillard brosse brouette bruyant bûche bulletin bureau
cabane cachette cadeau cahier caillou calcul calendrier camarade campagne canapé canard caramel carotte carrefour carrosse cartable casquette casserole catastrophe cauchemar ceinture célèbre cendre cerise chaise chameau champignon chandelle chanson chapeau chapitre charrette château chaussette chemise chenille cheminée chevalier cheveux chèvre chocolat chouette ciseaux citrouille clarinette clavier climat coccinelle cochon colline colonne commencer commerce comment commode compagnon comprendre compter concert confiture connaître conseil conte content corbeau corridor costume côtelette couleur couronne courage courrier couteau couvercle couverture crayon crocodile croissant cuillère cuisine cuisinier curieux cygne cylindre
danger danseuse dauphin débutant décembre décorer défendre déguisement déjeuner délicieux demain dentifrice dépenser désert dessert dessiner détective deviner diamant dictionnaire difficile dimanche dinosaure diplôme discours discussion distance docteur dommage donner dragon drapeau dromadaire
écharpe échelle éclair école écorce écureuil écriture effacer effort église élastique éléphant élève embrasser émission emmener empêcher emporter encre enfance enfant ennemi ennuyer enveloppe épaule épice épingle éponge équipe erreur escalier escargot espace espoir essence essuyer étagère étoile étrange étrangère exemple exercice explication explorer exposition
facile facteur famille fantôme farine fauteuil félicitations fenêtre fermier feuille ficelle fièvre figure filet fillette flamme flèche fleuve flocon fontaine football forêt fougère fourmi fourneau fraise framboise frapper frisson fromage fumée fusée
galette garçon gâteau gauche gazelle gendarme genou géant gentil géographie girafe glaçon gomme gorille goûter graine grammaire grenier grenouille griffe grimace guêpe guirlande guitare gymnase
habiller habitant habitude hamster haricot hélicoptère herbe hérisson heureux hibou hirondelle histoire hiver homme honnête hôpital horloge horizon hôtel huile humeur
igloo image immense immeuble important imprimer incendie inconnu indien infirmière insecte instant intelligent intérieur invitation
jambon jardin jardinier jeudi jongleur journal journée joyeux juillet jument jungle
kangourou kilomètre
laboratoire labyrinthe lacet laitue lampadaire lanterne lapin lavabo leçon légume lendemain lettre libellule librairie lion liquide litre livre locomotive longtemps lumière lundi lunettes
machine magasin magicien magnifique maillot maintenant mairie maison maîtresse malade malheur manège manteau marelle marmotte marteau matelas médaille médecin mélange mensonge menuisier merveille message métier météo mètre meuble midi miroir mission mitaine moineau monnaie montagne monument mouchoir mouette moustache mouton moyen muguet multiplication muscle musée musique mystère
nageur naissance nappe navire neige nettoyer neveu noisette nombre nourrir nuage
objet occasion océan odeur oiseau omelette ongle opinion orange orchestre ordinateur oreille oreiller orteil otarie ours outil ouvrier
paillasson panier pantalon papillon paquet parapluie parc pareil paresseux parfum passage passager passerelle patience patinage pêcheur peigne peinture pelouse pendule perroquet personne pharmacie phoque photographie piano pieuvre pinceau pingouin pique-nique pirate piscine placard plafond planète plateau pluie plumage poignée poisson poivre pommade pompier pont portail portefeuille poubelle poule poussière pourquoi poussin prairie premier princesse printemps problème programme promenade prudent puissant pull pyramide pyjama
quartier question queue quinze quotidien
raccourci racine radiateur raisin rallonge randonnée rangement rapide raquette rateau récréation réfrigérateur regarder règle reine remarque rencontre renard repas rhinocéros rideau rivière robinet rocher rossignol roulotte royaume rythme
sable sabot saison salade salle samedi sandale sapin sauterelle sauvage savon scène scie scorpion secret semaine sentier septembre serpent serrure serviette siècle sifflet silence singe sirène skieur soleil sommeil sommet sorcier soupe sourire souris souvenir spectacle squelette statue stylo succès sucre supermarché surprise symbole sympathique système
tableau tablier tambour tapis tasse téléphone télévision tempête terrain terrasse territoire théâtre thermomètre tigre tirelire tissu toboggan tomate tonnerre tortue toujours tournesol tracteur tranquille travail trésor tribu triangle trompette trottinette trousse tulipe tunnel tuyau
uniforme univers usine utile
vacances vache vaisselle valise vallée vapeur végétal vélo vendredi verger vêtement viande victoire village violon visage vitrine voisin voiture volcan voyage
wagon xylophone yaourt zèbre zéro
abondance accessoire acquérir adolescent agriculteur aiguiser allergie ambition amphithéâtre ancienneté apparition appréciation approximatif aquatique arrondissement assemblée association atmosphère attraction automobile autorisation avertissement
barrage bénévole bienveillance boulangerie bouleversement brillamment cérémonie chronologie circonférence civilisation collectionner commerçant commission communication compétition complication comportement concurrence condition connaissance conséquence considérable construction conversation coopération correspondance croissance cultivateur
dangereusement décision décoration dégoûtant démocratie déménagement dénombrement dépannage développement difficulté dimension direction disparition dissimuler distribution documentaire domicile
efficace électricité élégance embarcation émotion empreinte encyclopédie énergie enthousiasme environnement équilibre équipement escalade essentiel établissement évaluation événement évidemment excellent exceptionnel expérience explosion expression extraordinaire
fabrication fermeture fréquemment frontière gouvernail gymnastique habitation harmonie hexagone hippopotame hypothèse illumination immédiatement impatience imperméable impression inattendu inquiétude installation instruction intéressant intermédiaire interruption intervention investigation irrégulier
journaliste langage législation littérature longitude manifestation mathématiques mécanicien mémoire microscope millionnaire mobilisation mouvement multitude
naturellement nécessaire négociation notamment nourrisson nutrition obstacle occupation officiellement opposition orthographe parallèle paragraphe parfaitement particulier patrimoine pédagogie permission phénomène philosophie physique planétarium population possession possibilité précipitation préhistoire présentation principalement probablement production profession progression proposition protection proximité psychologue publicité
réalisation recommandation reconnaissance rectangle réflexion règlement remarquable renseignement répartition reproduction résistance respiration restaurant rhumatisme
satellite scientifique sécurité sensibilité silhouette simultanément situation solitude sympathie symétrie technique température tolérance tranquillité transmission transparence transport traversée tremblement tyrannosaure
université utilisation vaccination végétation vérification vocabulaire volontaire
"""
